#!/bin/bash
../PRSolve --verbose --obs ARL82660.09o \
   --eph igs15502.sp3,igs15503.sp3,igs15504.sp3 \
   --eph igl15502.sp3,igl15503.sp3,igl15504.sp3 \
   --clk igs15502.clk_30s,igs15503.clk_30s,igs15504.clk_30s \
   --clk esa15502.clk,esa15503.clk,esa15504.clk \
   --ref -740311.8581,-5457066.4731,3207249.3343:%x,%y,%z \
   --sol GPS:12:WC,GLO:12:PC,GPS+GLO:12:WC+PC \
   "$@"

../PRSplot.pl --tag RNE pos clk dop rms
   
# test with broadcast ephemeris
../PRSolve --verbose --log prs_brc.log \
   --obs ARL82660.09o --nav ARL82660.09N \
   --ref -740311.8581,-5457066.4731,3207249.3343:%x,%y,%z \
   --sol GPS:12:WC \
   "$@"
   #not yet --nav ARL82660.09G --nav ARL82660.09H \

../PRSplot.pl --file prs_brc.log --tag RNE pos clk dop rms
