import sys
import shutil
import os
from distutils.core import setup, Extension


core_lib =  ['apps/bindings_installer/gpstk/gpstk_pylibPYTHON_wrap.cxx',
            'src/AlmOrbit.cpp',
            'src/ANSITime.cpp',
            'src/AstronomicalFunctions.cpp',
            'src/BinUtils.cpp',
            'src/BrcClockCorrection.cpp',
            'src/BrcKeplerOrbit.cpp',
            'src/CivilTime.cpp',
            'src/ClockSatStore.cpp',
            'src/CommonTime.cpp',
            'src/EngAlmanac.cpp',
            'src/EngEphemeris.cpp',
            'src/EngNav.cpp',
            'src/Exception.cpp',
            'src/FFData.cpp',
            'src/FFStream.cpp',
            'src/GalEphemeris.cpp',
            'src/GalEphemerisStore.cpp',
            'src/GloEphemeris.cpp',
            'src/GloEphemerisStore.cpp',
            'src/GPSAlmanacStore.cpp',
            'src/GPSEphemerisStore.cpp',
            'src/GPSWeek.cpp',
            'src/GPSWeekSecond.cpp',
            'src/GPSWeekZcount.cpp',
            'src/GPSZcount.cpp',
            'src/JulianDate.cpp',
            'src/MJD.cpp',
            'src/ObsEpochMap.cpp',
            'src/ObsID.cpp',
            'src/ObsIDInitializer.cpp',
            'src/OrbElem.cpp',
            'src/OrbElemRinex.cpp',
            'src/Position.cpp',
            'src/PositionSatStore.cpp',
            'src/PRSolution2.cpp',
            'src/ReferenceFrame.cpp',
            'src/Rinex3ClockData.cpp',
            'src/Rinex3ClockHeader.cpp',
            'src/Rinex3EphemerisStore.cpp',
            'src/Rinex3NavData.cpp',
            'src/Rinex3NavHeader.cpp',
            'src/Rinex3ObsData.cpp',
            'src/Rinex3ObsHeader.cpp',
            'src/RinexClockData.cpp',
            'src/RinexClockHeader.cpp',
            'src/RinexMetData.cpp',
            'src/RinexMetHeader.cpp',
            'src/RinexNavData.cpp',
            'src/RinexNavHeader.cpp',
            'src/RinexObsData.cpp',
            'src/RinexObsHeader.cpp',
            'src/RinexObsID.cpp',
            'src/RinexSatID.cpp',
            'src/RinexUtilities.cpp',
            'src/SEMAlmanacStore.cpp',
            'src/SEMData.cpp',
            'src/SEMHeader.cpp',
            'src/SP3Data.cpp',
            'src/SP3EphemerisStore.cpp',
            'src/SP3Header.cpp',
            'src/SP3SatID.cpp',
            'src/SVNumXRef.cpp',
            'src/SystemTime.cpp',
            'src/TimeConverters.cpp',
            'src/TimeString.cpp',
            'src/TimeSystem.cpp',
            'src/TimeTag.cpp',
            'src/Triple.cpp',
            'src/TropModel.cpp',
            'src/UnixTime.cpp',
            'src/WxObsMap.cpp',
            'src/Xvt.cpp',
            'src/YDSTime.cpp',
            'src/YumaAlmanacStore.cpp',
            'src/YumaData.cpp',
            ]


def main():
      setup(name='gpstk',
            version='2.1',
            description='The GPS Toolkit',
            author='Applied Research Laboratories at the University of Texas at Austin',
            author_email='gpstk@arlut.utexas.edu',
            url='http://www.gpstk.org/',
            package_dir={'gpstk': 'apps/bindings_installer/gpstk'},
            ext_modules=[Extension(name='gpstk._gpstk_pylib',
                                   sources=core_lib,
                                   extra_compile_args=['-std=c++11', '-w'],
                                   language='c++')],
            packages=['gpstk', 'gpstk.cpp', 'gpstk.constants', 'gpstk.exceptions'],
            )

if __name__ == '__main__':
      main()
