#!/usr/env python

import sys
import argparse
import unittest

parser = argparse.ArgumentParser(description="Test app for ctest")
parser.add_argument('-v,--verbose', dest='verbose', action='count',
                    help="Increase the amount of output generated by the program")
parser.add_argument('swig_module_dir', metavar='dir',
                    help="Path to swig module.")
parser.add_argument('-o,--output_dir', dest='output_dir', metavar='dir',
                    help="Path to output directory")
parser.add_argument('-i,--input_dir', dest='input_dir', metavar='dir',
                    help="Path to root of input data directory")

args=parser.parse_args()

sys.path=[args.swig_module_dir]+sys.path
if args.verbose:
    print "Using gpstk bindings at {}".format(args.swig_module_dir)

def run_unit_tests(testCase):
    """A function to run unit tests without using the argument parsing of
    unittest.main() """
    runner=unittest.TextTestRunner()
    isuite = unittest.TestLoader().loadTestsFromTestCase(testCase)
    rc = runner.run(isuite)
    sys.exit(len(rc.errors))
