import sys
from distutils.core import setup, Extension


# 1. Make sure there are no duplicates in this list
# 2. Do not include header files in this list, only .cpp files
core_lib =  ['gpstk.i',
            '../../../src/AlmOrbit.cpp',
             '../../../src/ANSITime.cpp',
             '../../../src/BinUtils.cpp',
             '../../../src/BrcClockCorrection.cpp',
             '../../../src/BrcKeplerOrbit.cpp',
             '../../../src/CivilTime.cpp',
             '../../../src/ClockSatStore.cpp',
             '../../../src/CommonTime.cpp',
             '../../../src/EngAlmanac.cpp',
             '../../../src/EngEphemeris.cpp',
             '../../../src/EngNav.cpp',
             '../../../src/Exception.cpp',
             '../../../src/FFData.cpp',
             '../../../src/FFStream.cpp',
             '../../../src/GalEphemeris.cpp',
             '../../../src/GalEphemerisStore.cpp',
             '../../../src/GPSAlmanacStore.cpp',
             '../../../src/GPSEphemerisStore.cpp',
             '../../../src/GPSWeek.cpp',
             '../../../src/GPSWeekSecond.cpp',
             '../../../src/GPSWeekZcount.cpp',
             '../../../src/GPSZcount.cpp',
             '../../../src/JulianDate.cpp',
             '../../../src/MJD.cpp',
             '../../../src/ObsID.cpp',
             '../../../src/ObsIDInitializer.cpp',
             '../../../src/Position.cpp',
             '../../../src/PositionSatStore.cpp',
             '../../../src/ReferenceFrame.cpp',
             '../../../src/Rinex3ClockData.cpp',
             '../../../src/Rinex3ClockHeader.cpp',
             '../../../src/Rinex3ObsHeader.cpp',
             '../../../src/RinexClockData.cpp',
             '../../../src/RinexClockHeader.cpp',
             '../../../src/RinexObsHeader.cpp',
             '../../../src/RinexObsID.cpp',
             '../../../src/RinexSatID.cpp',
             '../../../src/SP3Data.cpp',
             '../../../src/SP3EphemerisStore.cpp',
             '../../../src/SP3Header.cpp',
             '../../../src/SP3SatID.cpp',
             '../../../src/SVNumXRef.cpp',
             '../../../src/SystemTime.cpp',
             '../../../src/TimeConverters.cpp',
             '../../../src/TimeString.cpp',
             '../../../src/TimeSystem.cpp',
             '../../../src/TimeTag.cpp',
             '../../../src/Triple.cpp',
             '../../../src/UnixTime.cpp',
             '../../../src/Xvt.cpp',
             '../../../src/YDSTime.cpp',
             '../../../src/YumaAlmanacStore.cpp',
             '../../../src/YumaData.cpp',
            ]



setup(name='GPSTk',
      version='2.1',
      description='The GPS Toolkit',
      author='Applied Research Laboratories at the University of Texas at Austin',
      author_email='gpstk@arlut.utexas.edu',
      url='http://www.gpstk.org/',
      ext_modules=[Extension(name='_gpstk',
                             sources=core_lib,
                             include_dirs=['../../../src/'],
                             extra_compile_args=['-std=c++11', '-Wunknown-pragmas'],
                             swig_opts=['-c++', '-I../include', '-w362,383,384,503'],
                             language='c++'
                            )
                  ],
      py_modules=['gpstk'],
     )