# This is an AUTO-GENERATED file by doc.py.
# Do not modify it unless you know what you are doing.
%include doc/Adler32_8cpp.i
%include doc/Adler32_8hpp.i
%include doc/AllanDeviation_8hpp.i
%include doc/AlmOrbit_8cpp.i
%include doc/AlmOrbit_8hpp.i
%include doc/AnotherFileFilterTest_8cpp.i
%include doc/ANSITime_8cpp.i
%include doc/ANSITime_8hpp.i
%include doc/Antenna_8cpp.i
%include doc/Antenna_8hpp.i
%include doc/AntexBase_8hpp.i
%include doc/AntexData_8cpp.i
%include doc/AntexData_8hpp.i
%include doc/AntexHeader_8cpp.i
%include doc/AntexHeader_8hpp.i
%include doc/AntexReader_8cpp.i
%include doc/AntexReader_8hpp.i
%include doc/AntexStream_8hpp.i
%include doc/ARBase_8cpp.i
%include doc/ARBase_8hpp.i
%include doc/ARLambda_8cpp.i
%include doc/ARLambda_8hpp.i
%include doc/ARMLambda_8cpp.i
%include doc/ARMLambda_8hpp.i
%include doc/ARSimple_8cpp.i
%include doc/ARSimple_8hpp.i
%include doc/ASConstant_8hpp.i
%include doc/AshtechALB_8cpp.i
%include doc/AshtechALB_8hpp.i
%include doc/AshtechData_8cpp.i
%include doc/AshtechData_8hpp.i
%include doc/AshtechEPB_8cpp.i
%include doc/AshtechEPB_8hpp.i
%include doc/AshtechMBEN_8cpp.i
%include doc/AshtechMBEN_8hpp.i
%include doc/AshtechPBEN_8cpp.i
%include doc/AshtechPBEN_8hpp.i
%include doc/AshtechStream_8hpp.i
%include doc/AstronomicalFunctions_8cpp.i
%include doc/AstronomicalFunctions_8hpp.i
%include doc/AtmosphericDrag_8cpp.i
%include doc/AtmosphericDrag_8hpp.i
%include doc/ATSData_8cpp.i
%include doc/ATSData_8hpp.i
%include doc/ATSStream_8hpp.i
%include doc/Axis_8cpp.i
%include doc/Axis_8hpp.i
%include doc/AxisStyle_8hpp.i
%include doc/Bancroft_8cpp.i
%include doc/Bancroft_8hpp.i
%include doc/Base64Encoder_8cpp.i
%include doc/Base64Encoder_8hpp.i
%include doc/BaseDistribution_8hpp.i
%include doc/BasicFramework_8cpp.i
%include doc/BasicFramework_8hpp.i
%include doc/BasicModel_8cpp.i
%include doc/BasicModel_8hpp.i
%include doc/BasicShape_8hpp.i
%include doc/BDSEphemeris_8cpp.i
%include doc/BDSEphemeris_8hpp.i
%include doc/BDSEphemerisStore_8cpp.i
%include doc/BDSEphemerisStore_8hpp.i
%include doc/BDSWeekSecond_8hpp.i
%include doc/BinexData_8cpp.i
%include doc/BinexData_8hpp.i
%include doc/BinexFilterOperators_8hpp.i
%include doc/BinexStream_8hpp.i
%include doc/BinUtils_8cpp.i
%include doc/BinUtils_8hpp.i
%include doc/Bitmap_8cpp.i
%include doc/Bitmap_8hpp.i
%include doc/BivarStats_8hpp.i
%include doc/BLQDataReader_8cpp.i
%include doc/BLQDataReader_8hpp.i
%include doc/BorderLayout_8cpp.i
%include doc/BorderLayout_8hpp.i
%include doc/BrcClockCorrection_8cpp.i
%include doc/BrcClockCorrection_8hpp.i
%include doc/BrcKeplerOrbit_8cpp.i
%include doc/BrcKeplerOrbit_8hpp.i
%include doc/Canvas_8cpp.i
%include doc/Canvas_8hpp.i
%include doc/CheckPRData_8hpp.i
%include doc/Chi2Distribution_8cpp.i
%include doc/Chi2Distribution_8hpp.i
%include doc/CiraExponentialDrag_8cpp.i
%include doc/CiraExponentialDrag_8hpp.i
%include doc/Circle_8hpp.i
%include doc/CivilTime_8cpp.i
%include doc/CivilTime_8hpp.i
%include doc/ClockModel_8hpp.i
%include doc/ClockSatStore_8cpp.i
%include doc/ClockSatStore_8hpp.i
%include doc/CNAV2EphClk_8cpp.i
%include doc/CNAV2EphClk_8hpp.i
%include doc/CNAVClock_8cpp.i
%include doc/CNAVClock_8hpp.i
%include doc/CNavDataElement_8cpp.i
%include doc/CNavDataElement_8hpp.i
%include doc/CNavDataElementStore_8cpp.i
%include doc/CNavDataElementStore_8hpp.i
%include doc/CNavEOP_8cpp.i
%include doc/CNavEOP_8hpp.i
%include doc/CNAVEphemeris_8cpp.i
%include doc/CNAVEphemeris_8hpp.i
%include doc/CNavGGTO_8cpp.i
%include doc/CNavGGTO_8hpp.i
%include doc/CNavISC_8cpp.i
%include doc/CNavISC_8hpp.i
%include doc/CNavText_8cpp.i
%include doc/CNavText_8hpp.i
%include doc/CNavUTC_8cpp.i
%include doc/CNavUTC_8hpp.i
%include doc/CodeBuffer_8cpp.i
%include doc/CodeBuffer_8hpp.i
%include doc/CodeKalmanSolver_8cpp.i
%include doc/CodeKalmanSolver_8hpp.i
%include doc/CodeSmoother_8cpp.i
%include doc/CodeSmoother_8hpp.i
%include doc/Color_8cpp.i
%include doc/Color_8hpp.i
%include doc/ColorMap_8cpp.i
%include doc/ColorMap_8hpp.i
%include doc/Combinations_8hpp.i
%include doc/CommandLine_8cpp.i
%include doc/CommandLine_8hpp.i
%include doc/CommandOption_8cpp.i
%include doc/CommandOption_8hpp.i
%include doc/CommandOptionParser_8cpp.i
%include doc/CommandOptionParser_8hpp.i
%include doc/CommandOptionWithCommonTimeArg_8cpp.i
%include doc/CommandOptionWithCommonTimeArg_8hpp.i
%include doc/CommandOptionWithPositionArg_8cpp.i
%include doc/CommandOptionWithPositionArg_8hpp.i
%include doc/CommandOptionWithTimeArg_8cpp.i
%include doc/CommandOptionWithTimeArg_8hpp.i
%include doc/Comment_8cpp.i
%include doc/Comment_8hpp.i
%include doc/CommonTime_8cpp.i
%include doc/CommonTime_8hpp.i
%include doc/compass__constants_8hpp.i
%include doc/ComputeCombination_8cpp.i
%include doc/ComputeCombination_8hpp.i
%include doc/ComputeDOP_8cpp.i
%include doc/ComputeDOP_8hpp.i
%include doc/ComputeIonoModel_8cpp.i
%include doc/ComputeIonoModel_8hpp.i
%include doc/ComputeIURAWeights_8cpp.i
%include doc/ComputeIURAWeights_8hpp.i
%include doc/ComputeLC_8cpp.i
%include doc/ComputeLC_8hpp.i
%include doc/ComputeLdelta_8cpp.i
%include doc/ComputeLdelta_8hpp.i
%include doc/ComputeLI_8cpp.i
%include doc/ComputeLI_8hpp.i
%include doc/ComputeLinear_8cpp.i
%include doc/ComputeLinear_8hpp.i
%include doc/ComputeMelbourneWubbena_8cpp.i
%include doc/ComputeMelbourneWubbena_8hpp.i
%include doc/ComputeMOPSWeights_8cpp.i
%include doc/ComputeMOPSWeights_8hpp.i
%include doc/ComputePC_8cpp.i
%include doc/ComputePC_8hpp.i
%include doc/ComputePdelta_8cpp.i
%include doc/ComputePdelta_8hpp.i
%include doc/ComputePI_8cpp.i
%include doc/ComputePI_8hpp.i
%include doc/ComputeSatPCenter_8cpp.i
%include doc/ComputeSatPCenter_8hpp.i
%include doc/ComputeSimpleWeights_8cpp.i
%include doc/ComputeSimpleWeights_8hpp.i
%include doc/ComputeTropModel_8cpp.i
%include doc/ComputeTropModel_8hpp.i
%include doc/ComputeWindUp_8cpp.i
%include doc/ComputeWindUp_8hpp.i
%include doc/ConfData_8hpp.i
%include doc/ConfDataItem_8hpp.i
%include doc/ConfDataReader_8cpp.i
%include doc/ConfDataReader_8hpp.i
%include doc/ConfDataSection_8hpp.i
%include doc/ConfDataStructures_8hpp.i
%include doc/ConfDataWriter_8cpp.i
%include doc/ConfDataWriter_8hpp.i
%include doc/ConstraintSystem_8cpp.i
%include doc/ConstraintSystem_8hpp.i
%include doc/ConvertC1ToP1_8cpp.i
%include doc/ConvertC1ToP1_8hpp.i
%include doc/convhelp_8hpp.i
%include doc/CorrectCodeBiases_8cpp.i
%include doc/CorrectCodeBiases_8hpp.i
%include doc/CorrectObservables_8cpp.i
%include doc/CorrectObservables_8hpp.i
%include doc/CRC32_8cpp.i
%include doc/CRC32_8hpp.i
%include doc/DataHeaders_8cpp.i
%include doc/DataHeaders_8hpp.i
%include doc/DataStatus_8hpp.i
%include doc/DataStructures_8cpp.i
%include doc/DataStructures_8hpp.i
%include doc/DayTimeConversionTest_8cpp.i
%include doc/DayTimeIncrementTest_8cpp.i
%include doc/DayTimeIncrementTest2_8cpp.i
%include doc/daytimetest_8cpp.i
%include doc/DayTimeToleranceTest_8cpp.i
%include doc/DCBDataReader_8cpp.i
%include doc/DCBDataReader_8hpp.i
%include doc/DDid_8cpp.i
%include doc/DDid_8hpp.i
%include doc/Decimate_8cpp.i
%include doc/Decimate_8hpp.i
%include doc/DeltaOp_8cpp.i
%include doc/DeltaOp_8hpp.i
%include doc/Differentiator_8cpp.i
%include doc/Differentiator_8hpp.i
%include doc/DiscCorr_8cpp.i
%include doc/DiscCorr_8hpp.i
%include doc/DOP_8cpp.i
%include doc/DOP_8hpp.i
%include doc/DoubleOp_8cpp.i
%include doc/DoubleOp_8hpp.i
%include doc/Dumper_8cpp.i
%include doc/Dumper_8hpp.i
%include doc/EarthBody_8cpp.i
%include doc/EarthBody_8hpp.i
%include doc/EarthOceanTide_8cpp.i
%include doc/EarthOceanTide_8hpp.i
%include doc/EarthOrientation_8cpp.i
%include doc/EarthOrientation_8hpp.i
%include doc/EarthPoleTide_8cpp.i
%include doc/EarthPoleTide_8hpp.i
%include doc/EarthSolidTide_8hpp.i
%include doc/EclipsedSatFilter_8cpp.i
%include doc/EclipsedSatFilter_8hpp.i
%include doc/EGM96GravityModel_8cpp.i
%include doc/EGM96GravityModel_8hpp.i
%include doc/EllipsoidModel_8hpp.i
%include doc/EngAlmanac_8cpp.i
%include doc/EngAlmanac_8hpp.i
%include doc/EngEphemeris_8cpp.i
%include doc/EngNav_8cpp.i
%include doc/EngEphemeris_8hpp.i
%include doc/EngNav_8hpp.i
%include doc/ENUUtil_8cpp.i
%include doc/ENUUtil_8hpp.i
%include doc/EOPDataStore_8cpp.i
%include doc/EOPDataStore_8hpp.i
%include doc/EphComp_8cpp.i
%include doc/EphemerisRange_8cpp.i
%include doc/EphemerisRange_8hpp.i
%include doc/EphReader_8cpp.i
%include doc/EphReader_8hpp.i
%include doc/Epoch_8cpp.i
%include doc/Epoch_8hpp.i
%include doc/EpochClockModel_8hpp.i
%include doc/EpochDataStore_8cpp.i
%include doc/EpochDataStore_8hpp.i
%include doc/EPSImage_8cpp.i
%include doc/EPSImage_8hpp.i
%include doc/Equation_8cpp.i
%include doc/Equation_8hpp.i
%include doc/EquationOfMotion_8hpp.i
%include doc/EquationSystem_8cpp.i
%include doc/EquationSystem_8hpp.i
%include doc/Exception_8cpp.i
%include doc/Exception_8hpp.i
%include doc/exceptiontest_8cpp.i
%include doc/expandtilde_8cpp.i
%include doc/expandtilde_8hpp.i
%include doc/lib_2Math_2Expression_8cpp.i
%include doc/removed_2apps_2qa_2Expression_8cpp.i
%include doc/lib_2Math_2Expression_8hpp.i
%include doc/removed_2apps_2qa_2Expression_8hpp.i
%include doc/ExtractCombinationData_8cpp.i
%include doc/ExtractCombinationData_8hpp.i
%include doc/ExtractData_8cpp.i
%include doc/ExtractData_8hpp.i
%include doc/ExtractLC_8hpp.i
%include doc/ExtractPC_8hpp.i
%include doc/FFBinaryStream_8hpp.i
%include doc/FFData_8cpp.i
%include doc/FFData_8hpp.i
%include doc/FFIdentifier_8cpp.i
%include doc/FFIdentifier_8hpp.i
%include doc/FFStream_8cpp.i
%include doc/FFStream_8hpp.i
%include doc/FFStreamError_8hpp.i
%include doc/FFTextStream_8hpp.i
%include doc/FICAStream_8hpp.i
%include doc/FICBase_8hpp.i
%include doc/FICData_8cpp.i
%include doc/FICData_8hpp.i
%include doc/FICData109_8cpp.i
%include doc/FICData109_8hpp.i
%include doc/FICData162_8cpp.i
%include doc/FICData162_8hpp.i
%include doc/FICData62_8cpp.i
%include doc/FICData62_8hpp.i
%include doc/FICData9_8cpp.i
%include doc/FICData9_8hpp.i
%include doc/FICFilterOperators_8hpp.i
%include doc/FICHeader_8cpp.i
%include doc/FICHeader_8hpp.i
%include doc/FICStream_8hpp.i
%include doc/FICStreamBase_8hpp.i
%include doc/FileFilter_8hpp.i
%include doc/FileFilterFrame_8hpp.i
%include doc/FileFilterFrameWithHeader_8hpp.i
%include doc/FileHunter_8cpp.i
%include doc/FileHunter_8hpp.i
%include doc/FileSpec_8cpp.i
%include doc/FileSpec_8hpp.i
%include doc/FileSpecTest_8cpp.i
%include doc/FileStore_8hpp.i
%include doc/FileUtils_8hpp.i
%include doc/Fillable_8hpp.i
%include doc/FilterBase_8hpp.i
%include doc/FIRDifferentiator5thOrder_8cpp.i
%include doc/FIRDifferentiator5thOrder_8hpp.i
%include doc/ForceModel_8hpp.i
%include doc/ForceModelList_8cpp.i
%include doc/ForceModelList_8hpp.i
%include doc/format_8cpp.i
%include doc/format_8hpp.i
%include doc/Frame_8cpp.i
%include doc/Frame_8hpp.i
%include doc/GalEphemeris_8cpp.i
%include doc/GalEphemeris_8hpp.i
%include doc/GalEphemerisStore_8cpp.i
%include doc/GalEphemerisStore_8hpp.i
%include doc/GALWeekSecond_8hpp.i
%include doc/GaussianDistribution_8cpp.i
%include doc/GaussianDistribution_8hpp.i
%include doc/GDSUtils_8hpp.i
%include doc/GeneralConstraint_8cpp.i
%include doc/GeneralConstraint_8hpp.i
%include doc/GeneralEquations_8cpp.i
%include doc/GeneralEquations_8hpp.i
%include doc/GenXSequence_8cpp.i
%include doc/GenXSequence_8hpp.i
%include doc/GeodeticFrames_8cpp.i
%include doc/GeodeticFrames_8hpp.i
%include doc/geometry_8hpp.i
%include doc/GloEphemeris_8cpp.i
%include doc/GloEphemeris_8hpp.i
%include doc/GloEphemerisStore_8cpp.i
%include doc/GloEphemerisStore_8hpp.i
%include doc/GloFreqIndex_8cpp.i
%include doc/GloFreqIndex_8hpp.i
%include doc/GNSSconstants_8hpp.i
%include doc/gps__constants_8hpp.i
%include doc/GPS__URA_8hpp.i
%include doc/GPSAlmanacStore_8cpp.i
%include doc/GPSAlmanacStore_8hpp.i
%include doc/GPSEllipsoid_8hpp.i
%include doc/GPSEphemeris_8cpp.i
%include doc/GPSEphemeris_8hpp.i
%include doc/GPSEphemerisStore_8cpp.i
%include doc/GPSEphemerisStore_8hpp.i
%include doc/GPSOrbElemStore_8cpp.i
%include doc/GPSOrbElemStore_8hpp.i
%include doc/gpstkplatform_8h.i
%include doc/GPSWeek_8cpp.i
%include doc/GPSWeek_8hpp.i
%include doc/GPSWeekSecond_8hpp.i
%include doc/GPSWeekZcount_8cpp.i
%include doc/GPSWeekZcount_8hpp.i
%include doc/GPSZcount_8cpp.i
%include doc/GPSZcount_8hpp.i
%include doc/gpszcounttest_8cpp.i
%include doc/GraphicsConstants_8cpp.i
%include doc/GraphicsConstants_8hpp.i
%include doc/GravitationalDelay_8cpp.i
%include doc/GravitationalDelay_8hpp.i
%include doc/GridLayout_8cpp.i
%include doc/GridLayout_8hpp.i
%include doc/GSatID_8cpp.i
%include doc/GSatID_8hpp.i
%include doc/HarrisPriesterDrag_8cpp.i
%include doc/HarrisPriesterDrag_8hpp.i
%include doc/HelmertTransform_8cpp.i
%include doc/HelmertTransform_8hpp.i
%include doc/Helper_8hpp.i
%include doc/HLayout_8cpp.i
%include doc/HLayout_8hpp.i
%include doc/IERS_8cpp.i
%include doc/IERS_8hpp.i
%include doc/IERSConventions_8cpp.i
%include doc/IERSConventions_8hpp.i
%include doc/InOutFramework_8hpp.i
%include doc/Integrator_8hpp.i
%include doc/InterpolatedColorMap_8cpp.i
%include doc/InterpolatedColorMap_8hpp.i
%include doc/IonexBase_8hpp.i
%include doc/IonexData_8cpp.i
%include doc/IonexData_8hpp.i
%include doc/IonexHeader_8cpp.i
%include doc/IonexHeader_8hpp.i
%include doc/IonexModel_8cpp.i
%include doc/IonexModel_8hpp.i
%include doc/IonexStore_8cpp.i
%include doc/IonexStore_8hpp.i
%include doc/IonexStream_8hpp.i
%include doc/IonoModel_8cpp.i
%include doc/IonoModel_8hpp.i
%include doc/IonoModelStore_8cpp.i
%include doc/IonoModelStore_8hpp.i
%include doc/JGM3GravityModel_8cpp.i
%include doc/JGM3GravityModel_8hpp.i
%include doc/JulianDate_8cpp.i
%include doc/JulianDate_8hpp.i
%include doc/KalmanFilter_8hpp.i
%include doc/Keeper_8cpp.i
%include doc/Keeper_8hpp.i
%include doc/KeplerOrbit_8cpp.i
%include doc/KeplerOrbit_8hpp.i
%include doc/Layout_8hpp.i
%include doc/LICSDetector_8cpp.i
%include doc/LICSDetector_8hpp.i
%include doc/LICSDetector2_8cpp.i
%include doc/LICSDetector2_8hpp.i
%include doc/Line_8cpp.i
%include doc/Line_8hpp.i
%include doc/LinearClockModel_8cpp.i
%include doc/LinearClockModel_8hpp.i
%include doc/LinearCombination_8cpp.i
%include doc/LinearCombination_8hpp.i
%include doc/LinearCombinations_8cpp.i
%include doc/LinearCombinations_8hpp.i
%include doc/LinePlot_8cpp.i
%include doc/LinePlot_8hpp.i
%include doc/Geomatics_2logstream_8hpp.i
%include doc/Utilities_2logstream_8hpp.i
%include doc/LoopedFramework_8cpp.i
%include doc/LoopedFramework_8hpp.i
%include doc/MainAdapter_8hpp.i
%include doc/Markable_8hpp.i
%include doc/Marker_8cpp.i
%include doc/Marker_8hpp.i
%include doc/MathBase_8hpp.i
%include doc/Matrix_8hpp.i
%include doc/MatrixBase_8hpp.i
%include doc/MatrixBaseOperators_8hpp.i
%include doc/MatrixFunctors_8hpp.i
%include doc/MatrixImplementation_8hpp.i
%include doc/MatrixOperators_8hpp.i
%include doc/MatrixTest_8cpp.i
%include doc/MDPHeader_8cpp.i
%include doc/MDPHeader_8hpp.i
%include doc/MDPNavSubframe_8cpp.i
%include doc/MDPNavSubframe_8hpp.i
%include doc/MDPObsEpoch_8cpp.i
%include doc/MJD_8cpp.i
%include doc/MDPObsEpoch_8hpp.i
%include doc/MDPPVTSolution_8cpp.i
%include doc/MDPPVTSolution_8hpp.i
%include doc/MDPSelftestStatus_8cpp.i
%include doc/MDPSelftestStatus_8hpp.i
%include doc/MDPStream_8hpp.i
%include doc/MemoryUtils_8hpp.i
%include doc/mergePCodeWords_8h.i
%include doc/MetReader_8cpp.i
%include doc/MetReader_8hpp.i
%include doc/MinSfTest_8cpp.i
%include doc/miscdefs_8hpp.i
%include doc/miscenum_8hpp.i
%include doc/MiscMath_8hpp.i
%include doc/MJD_8hpp.i
%include doc/ModeledPR_8cpp.i
%include doc/ModeledPR_8hpp.i
%include doc/ModeledPseudorangeBase_8hpp.i
%include doc/ModeledReferencePR_8cpp.i
%include doc/ModeledReferencePR_8hpp.i
%include doc/ModelObs_8cpp.i
%include doc/ModelObs_8hpp.i
%include doc/ModelObsFixedStation_8cpp.i
%include doc/ModelObsFixedStation_8hpp.i
%include doc/MoonForce_8cpp.i
%include doc/MoonForce_8hpp.i
%include doc/MoonPosition_8cpp.i
%include doc/MoonPosition_8hpp.i
%include doc/MOPSWeight_8cpp.i
%include doc/MOPSWeight_8hpp.i
%include doc/MSCBase_8hpp.i
%include doc/oae_8cpp.i
%include doc/MSCData_8cpp.i
%include doc/MSCData_8hpp.i
%include doc/MSCHeader_8hpp.i
%include doc/MSCStore_8cpp.i
%include doc/MSCStore_8hpp.i
%include doc/MSCStream_8hpp.i
%include doc/Msise00Drag_8cpp.i
%include doc/Msise00Drag_8hpp.i
%include doc/MWCSDetector_8cpp.i
%include doc/MWCSDetector_8hpp.i
%include doc/NablaOp_8cpp.i
%include doc/NablaOp_8hpp.i
%include doc/lib_2Math_2Namelist_8cpp.i
%include doc/removed_2lib_2Geomatics_2Namelist_8cpp.i
%include doc/lib_2Math_2Namelist_8hpp.i
%include doc/removed_2lib_2Geomatics_2Namelist_8hpp.i
%include doc/NEDUtil_8cpp.i
%include doc/NEDUtil_8hpp.i
%include doc/NetworkObsStreams_8cpp.i
%include doc/NetworkObsStreams_8hpp.i
%include doc/NovatelData_8cpp.i
%include doc/NovatelData_8hpp.i
%include doc/NovatelStream_8hpp.i
%include doc/ObsArray_8cpp.i
%include doc/ObsArray_8hpp.i
%include doc/ObsClockModel_8cpp.i
%include doc/ObsClockModel_8hpp.i
%include doc/ObsEphReaderFramework_8cpp.i
%include doc/ObsEphReaderFramework_8hpp.i
%include doc/ObsEpochMap_8cpp.i
%include doc/ObsEpochMap_8hpp.i
%include doc/ObsID_8cpp.i
%include doc/ObsID_8hpp.i
%include doc/ObsIDInitializer_8cpp.i
%include doc/ObsIDInitializer_8hpp.i
%include doc/ObsReader_8cpp.i
%include doc/ObsReader_8hpp.i
%include doc/obsrip_8cpp.i
%include doc/ObsRngDev_8cpp.i
%include doc/ObsRngDev_8hpp.i
%include doc/ObsUtils_8cpp.i
%include doc/ObsUtils_8hpp.i
%include doc/lib_2GNSSCore_2OceanLoading_8cpp.i
%include doc/removed_2lib_2Geomatics_2OceanLoading_8cpp.i
%include doc/lib_2GNSSCore_2OceanLoading_8hpp.i
%include doc/removed_2lib_2Geomatics_2OceanLoading_8hpp.i
%include doc/OneFreqCSDetector_8cpp.i
%include doc/OneFreqCSDetector_8hpp.i
%include doc/OrbElem_8cpp.i
%include doc/OrbElem_8hpp.i
%include doc/OrbElemCNAV_8cpp.i
%include doc/OrbElemCNAV_8hpp.i
%include doc/OrbElemCNAV2_8cpp.i
%include doc/OrbElemCNAV2_8hpp.i
%include doc/OrbElemFIC109_8cpp.i
%include doc/OrbElemFIC109_8hpp.i
%include doc/OrbElemFIC9_8cpp.i
%include doc/OrbElemFIC9_8hpp.i
%include doc/OrbElemICE_8cpp.i
%include doc/OrbElemICE_8hpp.i
%include doc/OrbElemLNav_8cpp.i
%include doc/OrbElemLNav_8hpp.i
%include doc/OrbElemRinex_8cpp.i
%include doc/OrbElemRinex_8hpp.i
%include doc/OrbElemStore_8hpp.i
%include doc/OrbitEph_8cpp.i
%include doc/OrbitEph_8hpp.i
%include doc/OrbitEphStore_8cpp.i
%include doc/OrbitEphStore_8hpp.i
%include doc/ORDEpoch_8hpp.i
%include doc/PackedNavBits_8cpp.i
%include doc/PackedNavBits_8hpp.i
%include doc/Palette_8cpp.i
%include doc/Palette_8hpp.i
%include doc/Path_8cpp.i
%include doc/Path_8hpp.i
%include doc/PCodeConst_8hpp.i
%include doc/PCSmoother_8cpp.i
%include doc/PCSmoother_8hpp.i
%include doc/petest_8cpp.i
%include doc/PhaseCodeAlignment_8cpp.i
%include doc/PhaseCodeAlignment_8hpp.i
%include doc/PhaseWindup_8cpp.i
%include doc/PhaseWindup_8hpp.i
%include doc/PlanetEphemeris_8cpp.i
%include doc/PlanetEphemeris_8hpp.i
%include doc/Plot_8cpp.i
%include doc/Plot_8hpp.i
%include doc/plottypes_8hpp.i
%include doc/PNG_8cpp.i
%include doc/PNG_8hpp.i
%include doc/PoleTides_8cpp.i
%include doc/PoleTides_8hpp.i
%include doc/PolyFit_8hpp.i
%include doc/Polygon_8hpp.i
%include doc/Position_8cpp.i
%include doc/Position_8hpp.i
%include doc/PositionSatStore_8cpp.i
%include doc/PositionSatStore_8hpp.i
%include doc/positiontest_8cpp.i
%include doc/PowerSum_8cpp.i
%include doc/PowerSum_8hpp.i
%include doc/PreciseRange_8cpp.i
%include doc/PreciseRange_8hpp.i
%include doc/ProblemSatFilter_8cpp.i
%include doc/ProblemSatFilter_8hpp.i
%include doc/ProcessingClass_8hpp.i
%include doc/ProcessingList_8cpp.i
%include doc/ProcessingList_8hpp.i
%include doc/ProcessingVector_8cpp.i
%include doc/ProcessingVector_8hpp.i
%include doc/PRSolution_8cpp.i
%include doc/PRSolution_8hpp.i
%include doc/PRSolution2_8cpp.i
%include doc/PRSolution2_8hpp.i
%include doc/Pruner_8cpp.i
%include doc/Pruner_8hpp.i
%include doc/PSImage_8cpp.i
%include doc/PSImage_8hpp.i
%include doc/PSImageBase_8cpp.i
%include doc/PSImageBase_8hpp.i
%include doc/PvtStore_8cpp.i
%include doc/PvtStore_8hpp.i
%include doc/PZ90Ellipsoid_8hpp.i
%include doc/QZSEphemeris_8cpp.i
%include doc/QZSEphemeris_8hpp.i
%include doc/QZSEphemerisStore_8cpp.i
%include doc/QZSEphemerisStore_8hpp.i
%include doc/QZSWeekSecond_8hpp.i
%include doc/RACRotation_8cpp.i
%include doc/RACRotation_8hpp.i
%include doc/random_8cpp.i
%include doc/random_8hpp.i
%include doc/Rectangle_8cpp.i
%include doc/Rectangle_8hpp.i
%include doc/ReferenceFrame_8cpp.i
%include doc/ReferenceFrame_8hpp.i
%include doc/ReferenceFrames_8cpp.i
%include doc/ReferenceFrames_8hpp.i
%include doc/RelativityEffect_8cpp.i
%include doc/RelativityEffect_8hpp.i
%include doc/RequireObservables_8cpp.i
%include doc/RequireObservables_8hpp.i
%include doc/Rinex3ClockBase_8hpp.i
%include doc/Rinex3ClockData_8cpp.i
%include doc/Rinex3ClockData_8hpp.i
%include doc/Rinex3ClockHeader_8cpp.i
%include doc/Rinex3ClockHeader_8hpp.i
%include doc/Rinex3ClockStream_8hpp.i
%include doc/Rinex3EphemerisStore_8cpp.i
%include doc/Rinex3EphemerisStore_8hpp.i
%include doc/Rinex3NavBase_8hpp.i
%include doc/Rinex3NavData_8cpp.i
%include doc/Rinex3NavData_8hpp.i
%include doc/Rinex3NavFilterOperators_8hpp.i
%include doc/Rinex3NavHeader_8cpp.i
%include doc/Rinex3NavHeader_8hpp.i
%include doc/Rinex3NavStream_8hpp.i
%include doc/Rinex3ObsBase_8hpp.i
%include doc/Rinex3ObsData_8cpp.i
%include doc/Rinex3ObsData_8hpp.i
%include doc/Rinex3ObsFilterOperators_8hpp.i
%include doc/Rinex3ObsHeader_8cpp.i
%include doc/Rinex3ObsHeader_8hpp.i
%include doc/Rinex3ObsStream_8hpp.i
%include doc/rinex__met__read__write_8cpp.i
%include doc/rinex__met__test_8cpp.i
%include doc/rinex__nav__read__write_8cpp.i
%include doc/rinex__nav__test_8cpp.i
%include doc/rinex__obs__read__write_8cpp.i
%include doc/rinex__obs__test_8cpp.i
%include doc/RinexClockBase_8hpp.i
%include doc/RinexClockData_8cpp.i
%include doc/RinexClockData_8hpp.i
%include doc/RinexClockHeader_8cpp.i
%include doc/RinexClockHeader_8hpp.i
%include doc/RinexClockStore_8hpp.i
%include doc/RinexClockStream_8hpp.i
%include doc/RinexConverters_8cpp.i
%include doc/RinexConverters_8hpp.i
%include doc/RinexEphemerisStore_8cpp.i
%include doc/RinexEphemerisStore_8hpp.i
%include doc/RinexMetBase_8hpp.i
%include doc/RinexMetData_8cpp.i
%include doc/RinexMetData_8hpp.i
%include doc/RinexMetFilterOperators_8hpp.i
%include doc/RinexMetHeader_8cpp.i
%include doc/RinexMetHeader_8hpp.i
%include doc/RinexMetStream_8hpp.i
%include doc/RinexNavBase_8hpp.i
%include doc/RinexNavData_8cpp.i
%include doc/RinexNavData_8hpp.i
%include doc/RinexNavFilterOperators_8hpp.i
%include doc/RinexNavHeader_8cpp.i
%include doc/RinexNavHeader_8hpp.i
%include doc/RinexNavStream_8hpp.i
%include doc/RinexObsBase_8hpp.i
%include doc/RinexObsData_8cpp.i
%include doc/RinexObsData_8hpp.i
%include doc/RinexObsFilterOperators_8hpp.i
%include doc/RinexObsHeader_8cpp.i
%include doc/RinexObsHeader_8hpp.i
%include doc/RinexObsID_8cpp.i
%include doc/RinexObsID_8hpp.i
%include doc/RinexObsStream_8hpp.i
%include doc/RinexSatID_8cpp.i
%include doc/RinexSatID_8hpp.i
%include doc/RinexUtilities_8cpp.i
%include doc/RinexUtilities_8hpp.i
%include doc/RK4VehicleModel_8cpp.i
%include doc/RK4VehicleModel_8hpp.i
%include doc/RobustStats_8cpp.i
%include doc/RobustStats_8hpp.i
%include doc/RTFileFrame_8hpp.i
%include doc/RungeKutta4_8cpp.i
%include doc/RungeKutta4_8hpp.i
%include doc/RungeKuttaFehlberg_8cpp.i
%include doc/RungeKuttaFehlberg_8hpp.i
%include doc/RungeKuttaTest_8cpp.i
%include doc/SatArcMarker_8cpp.i
%include doc/SatArcMarker_8hpp.i
%include doc/SatDataReader_8cpp.i
%include doc/SatDataReader_8hpp.i
%include doc/SatID_8hpp.i
%include doc/SatOrbit_8cpp.i
%include doc/SatOrbit_8hpp.i
%include doc/SatOrbitPropagator_8cpp.i
%include doc/SatOrbitPropagator_8hpp.i
%include doc/SatPass_8cpp.i
%include doc/SatPass_8hpp.i
%include doc/ScatterPlot_8cpp.i
%include doc/ScatterPlot_8hpp.i
%include doc/SEMAlmanacStore_8cpp.i
%include doc/SEMAlmanacStore_8hpp.i
%include doc/SEMBase_8hpp.i
%include doc/SEMData_8cpp.i
%include doc/SEMData_8hpp.i
%include doc/SEMHeader_8cpp.i
%include doc/SEMHeader_8hpp.i
%include doc/SEMStream_8hpp.i
%include doc/SeriesList_8cpp.i
%include doc/SeriesList_8hpp.i
%include doc/SimpleFilter_8cpp.i
%include doc/SimpleFilter_8hpp.i
%include doc/SimpleIURAWeight_8cpp.i
%include doc/SimpleIURAWeight_8hpp.i
%include doc/SimpleKalmanFilter_8cpp.i
%include doc/SimpleKalmanFilter_8hpp.i
%include doc/Geomatics_2singleton_8hpp.i
%include doc/Utilities_2singleton_8hpp.i
%include doc/SMODFData_8cpp.i
%include doc/SMODFData_8hpp.i
%include doc/SMODFStream_8hpp.i
%include doc/SolarPosition_8cpp.i
%include doc/SolarPosition_8hpp.i
%include doc/SolarRadiationPressure_8cpp.i
%include doc/SolarRadiationPressure_8hpp.i
%include doc/SolarSystem_8cpp.i
%include doc/SolarSystem_8hpp.i
%include doc/SolidEarthTides_8cpp.i
%include doc/SolidEarthTides_8hpp.i
%include doc/SolidTides_8cpp.i
%include doc/SolidTides_8hpp.i
%include doc/SolverBase_8hpp.i
%include doc/SolverGeneral_8cpp.i
%include doc/SolverGeneral_8hpp.i
%include doc/SolverLMS_8cpp.i
%include doc/SolverLMS_8hpp.i
%include doc/SolverPPP_8cpp.i
%include doc/SolverPPP_8hpp.i
%include doc/SolverPPPFB_8cpp.i
%include doc/SolverPPPFB_8hpp.i
%include doc/SolverWMS_8cpp.i
%include doc/SolverWMS_8hpp.i
%include doc/SourceID_8cpp.i
%include doc/SourceID_8hpp.i
%include doc/SP3Base_8hpp.i
%include doc/SP3Data_8cpp.i
%include doc/SP3Data_8hpp.i
%include doc/SP3EphemerisStore_8cpp.i
%include doc/SP3EphemerisStore_8hpp.i
%include doc/SP3Header_8cpp.i
%include doc/SP3Header_8hpp.i
%include doc/SP3SatID_8cpp.i
%include doc/SP3SatID_8hpp.i
%include doc/SP3Stream_8hpp.i
%include doc/Spacecraft_8cpp.i
%include doc/Spacecraft_8hpp.i
%include doc/SparseBinnedStats_8hpp.i
%include doc/SpecialFunctions_8cpp.i
%include doc/Geomatics_2SpecialFunctions_8hpp.i
%include doc/Math_2SpecialFunctions_8hpp.i
%include doc/SphericalHarmonicGravity_8cpp.i
%include doc/SphericalHarmonicGravity_8hpp.i
%include doc/Splitter_8cpp.i
%include doc/Splitter_8hpp.i
%include doc/SRI_8cpp.i
%include doc/SRI_8hpp.i
%include doc/SRIFilter_8cpp.i
%include doc/SRIFilter_8hpp.i
%include doc/SRIleastSquares_8cpp.i
%include doc/SRIleastSquares_8hpp.i
%include doc/SRIMatrix_8hpp.i
%include doc/Stats_8hpp.i
%include doc/stl__helpers_8hpp.i
%include doc/StochasticModel_8cpp.i
%include doc/StochasticModel_8hpp.i
%include doc/Text_8cpp.i
%include doc/StreamBuf_8hpp.i
%include doc/StringUtils_8hpp.i
%include doc/stringutiltest_8cpp.i
%include doc/StrokeStyle_8cpp.i
%include doc/StrokeStyle_8hpp.i
%include doc/StudentDistribution_8cpp.i
%include doc/StudentDistribution_8hpp.i
%include doc/SunEarthSatGeometry_8cpp.i
%include doc/SunEarthSatGeometry_8hpp.i
%include doc/SunForce_8cpp.i
%include doc/SunForce_8hpp.i
%include doc/SunPosition_8cpp.i
%include doc/SunPosition_8hpp.i
%include doc/SurfacePlot_8cpp.i
%include doc/SurfacePlot_8hpp.i
%include doc/SVExclusionList_8cpp.i
%include doc/SVExclusionList_8hpp.i
%include doc/SVGImage_8cpp.i
%include doc/SVGImage_8hpp.i
%include doc/SVNumXRef_8cpp.i
%include doc/SVNumXRef_8hpp.i
%include doc/SVPCodeGen_8cpp.i
%include doc/SVPCodeGen_8hpp.i
%include doc/Synchronize_8cpp.i
%include doc/Synchronize_8hpp.i
%include doc/SystemTime_8cpp.i
%include doc/SystemTime_8hpp.i
%include doc/TabularSatStore_8hpp.i
%include doc/testExpression_8cpp.i
%include doc/Text_8hpp.i
%include doc/TextStyle_8cpp.i
%include doc/TextStyle_8hpp.i
%include doc/TimeConstants_8hpp.i
%include doc/TimeConverters_8cpp.i
%include doc/TimeConverters_8hpp.i
%include doc/TimeNamedFileStream_8hpp.i
%include doc/TimeString_8cpp.i
%include doc/TimeString_8hpp.i
%include doc/TimeSystem_8cpp.i
%include doc/TimeSystem_8hpp.i
%include doc/TimeSystemCorr_8hpp.i
%include doc/TimeTag_8cpp.i
%include doc/TimeTag_8hpp.i
%include doc/TimeTest_8cpp.i
%include doc/Triple_8cpp.i
%include doc/Triple_8hpp.i
%include doc/TropModel_8cpp.i
%include doc/TropModel_8hpp.i
%include doc/TypeID_8cpp.i
%include doc/TypeID_8hpp.i
%include doc/UnixTime_8cpp.i
%include doc/UnixTime_8hpp.i
%include doc/UTCTime_8cpp.i
%include doc/UTCTime_8hpp.i
%include doc/ValarrayUtils_8hpp.i
%include doc/ValidType_8hpp.i
%include doc/Variable_8cpp.i
%include doc/Variable_8hpp.i
%include doc/VDrawException_8hpp.i
%include doc/Vector_8hpp.i
%include doc/VectorBase_8cpp.i
%include doc/VectorBase_8hpp.i
%include doc/VectorBaseOperators_8hpp.i
%include doc/VectorOperators_8hpp.i
%include doc/VGImage_8cpp.i
%include doc/VGImage_8hpp.i
%include doc/VGState_8hpp.i
%include doc/ViewerManager_8cpp.i
%include doc/ViewerManager_8hpp.i
%include doc/VLayout_8cpp.i
%include doc/VLayout_8hpp.i
%include doc/Week_8cpp.i
%include doc/Week_8hpp.i
%include doc/WeekSecond_8cpp.i
%include doc/WeekSecond_8hpp.i
%include doc/WeightBase_8hpp.i
%include doc/WGS84Ellipsoid_8hpp.i
%include doc/WxObsMap_8cpp.i
%include doc/WxObsMap_8hpp.i
%include doc/X1Sequence_8cpp.i
%include doc/X1Sequence_8hpp.i
%include doc/X2Sequence_8cpp.i
%include doc/X2Sequence_8hpp.i
%include doc/Xbegweek_8cpp.i
%include doc/Xendweek_8cpp.i
%include doc/Xv_8hpp.i
%include doc/Xvt_8cpp.i
%include doc/Xvt_8hpp.i
%include doc/XvtStore_8hpp.i
%include doc/XYZ2NED_8cpp.i
%include doc/XYZ2NED_8hpp.i
%include doc/XYZ2NEU_8cpp.i
%include doc/XYZ2NEU_8hpp.i
%include doc/YDSTime_8cpp.i
%include doc/YDSTime_8hpp.i
%include doc/YumaAlmanacStore_8cpp.i
%include doc/YumaAlmanacStore_8hpp.i
%include doc/YumaBase_8hpp.i
%include doc/YumaData_8cpp.i
%include doc/YumaData_8hpp.i
%include doc/YumaHeader_8hpp.i
%include doc/YumaStream_8hpp.i
%include doc/dir_14dc9cec7f24281388aa625d58885d20.i
%include doc/dir_9c7a9bd828ac0825371bbe88048c6752.i
%include doc/dir_fbfddd7ae565a07501dcdd5f7248dc0b.i
%include doc/dir_b08c18aafa8dbed8a74e74c7618bba98.i
%include doc/dir_1e8ad0574bd6e387992681ee57691a07.i
%include doc/dir_c0f55812190c3a51294d56d000d7fd9a.i
%include doc/dir_e699485dc7f0b7b0e3c026cb80fdafc6.i
%include doc/dir_15c5639bd73b7993137d3a9ac8a02efe.i
%include doc/dir_aa9b079ea1066c8d7975aa6e481176a0.i
%include doc/dir_208fca0a515557dbc291f9340fad73d1.i
%include doc/dir_e3f013e9977780516b630649cd3d4c18.i
%include doc/dir_7c86f651b938876a4dba2ded1facaee1.i
%include doc/dir_05856167b4d10e8ea85e393d571d8711.i
%include doc/dir_eee19a531c656634383ea339f83633ec.i
%include doc/dir_0c03e20a93c9f942bb66cbdb33430001.i
%include doc/dir_fd1442b5d8a000f716b8647df6970647.i
%include doc/dir_9206bafbfaa29c27abc4798cf3e95709.i
%include doc/dir_97aefd0d527b934f1d99a682da8fe6a9.i
%include doc/dir_ba4abd708f97df51d396cdd44ef5cde6.i
%include doc/dir_885fc5aef1439cb5a180afa3f5f5ce18.i
%include doc/dir_d02fe1ac057fe8175ade5a5ea65b39ba.i
%include doc/dir_fe4282478cae6b81419d337a3b856319.i
%include doc/dir_3b7fb3e9753a6313665044788ef40504.i
%include doc/dir_ca94aa0795c59386089ea07af2643a2e.i
%include doc/dir_9ea0c25222703c83faccb6a8caf2b250.i
%include doc/dir_b8c2f5b0af94dc1ea437e7b5429a0d4b.i
%include doc/dir_08334539fb24ace7cad7f9ba2aac0689.i
%include doc/dir_facf6960b32d5a42987cd6ac57e92454.i
%include doc/dir_28998a5b7d9d6b404ab27346502f9522.i
%include doc/dir_0adb7c4e8dfc9d0a51388699c8e61e73.i
%include doc/dir_b52c2246d8a169e02be436b681d283d4.i
%include doc/dir_35e8a6e5d1b490a545fe1ae4405ed98d.i
%include doc/dir_59c2b139217198e8c262946c168bac67.i
%include doc/dir_30e48bd1c195de96d54a59e0ab0c3bfb.i
%include doc/dir_8d279c394f13ea23dc8dc890fd5237d0.i
%include doc/dir_105ab52e7dec2177e1a719be28c467a5.i
%include doc/dir_8957f9756d7925cebb122bb126e5e70f.i
%include doc/dir_f5cb60d758841a9d5511a46e6c4ef5de.i
%include doc/dir_4782ee714e036e6a98d05897fcd60469.i
%include doc/dir_ff73dac1c20e88b249e900f2c886d6ec.i
%include doc/dir_4b92a8fd266c092f0cc085ae682f43fd.i
