// GPSTk wrap for exception.cpp

%module gpstk

%include "gpstk_AllanDeviation.i"
%include "gpstk_AlmOrbit.i"
%include "gpstk_ANSITime.i"
%include "gpstk_Antenna.i"
//%include "gpstk_
//%include "gpstk_
%include "gpstk_BaseDistribution.i"
%include "gpstk_BasicFrameWork.i"
%include "gpstk_BinexData.i"
%include "gpstk_BinexFilterOperators.i"
%include "gpstk_BinexStream.i"
%include "gpstk_BivarStats.i"
%include "gpstk_
%include "gpstk_CheckPRData.i"
%include "gpstk_ClockModel.i"
%include "gpstk_CodeBuffer.i"
%include "gpstk_CommandOptionsParser.i"
%include "gpstk_CommonTime.i"
%inlcude "gpstk_ConfDataReader.i"
%include "gpstk_convhelp.i"
%include "gpstk_DayTime.i"
//%include "gpstk_
%include "gpstk_EllipsoidModel.i"
%include "gpstk_ENUUtil.i"
//%include "gpstk_
%include "gpstk_exception.i"
%include "gpstk_Expression.i"
%include "gpstk_ExtractC1.i"
%include "gpstk_ExtractCombinationData.i"
%include "gpstk_ExtractD1.i"
%include "gpstk_ExtractD2.i"
%include "gpstk_ExtractData.i"
%include "gpstk_ExtractL1.i"
%include "gpstk_ExtractL2.i"
%include "gpstk_ExtractLC.i"
%include "gpstk_ExtractP1.i"
%include "gpstk_ExtractP2.i"
%include "gpstk_ExtractPC.i"
%include "gpstk_FFBinaryStream.i"
%include "gpstk_FFData.i"
%include "gpstk_FFStream.i"
%include "gpstk_FFStreamError.i"
%include "gpstk_FFTextStream.i"
%include "gpstk_FICAStream.i"
%include "gpstk_FICBase.i"
%include "gpstk_FICDataSet.i
%include "gpstk_FICFilterOperators.i"
//%include "gpstk_
%include "gpstk_FICStream.i"
%include "gpstk_FICStreamBase.i"
%include "gpstk_FileFilter.i"
%include "gpstk_FileFilterFrame.i"
%include "gpstk_FileFilterFrameWithHeader.i"
%include "gpstk_FileHunter.i"
%include "gpstk_FileSpec.i"
%include "gpstk_FileStore.i"
%include "gpstk_FileUtils.i"
%include "gpstk_GaussianDistribution.i"
%include "gpstk_GenXSequence.i"
%include "gpstk_Geodetic.i"
%include "gpstk_GeoidModel.i"
%include "gpstk_geometry.i"
%include "gpstk_GPSAlmanacStore.i"
%include "gpstk_gps_constants.i"
%include "gpstk_GPSEllipsoid.i"
%include "gpstk_GPSEphemerisStore.i"
%include "gpstk_GPSGeoid.i"
%include "gpstk_GPSWeek.i"
//%include "gpstk_
%include "gpstk_GPSZcount.i"
%include "gpstk_icd_200_constants.i"
%include "gpstk_InOutFramework.i"
%include "gpstk_IonexBase.i"
%include "gpstk_
//%include "gpstk_
%include "gpstk_IonexStore.i"
%include "gpstk_IonexStream.i"
%include "gpstk_IonoModel.i"
%include "gpstk_IonoModelStore.i"
%include "gpstk_JulianDate.i"
%include "gpstk_LinearClockModel.i"
%include "gpstk_LoopedFramework.i"
%include "gpstk_Matrix.i"
%include "gpstk_MatrixBase.i"
//%include "gpstk_
//%include "gpstk_
%include "gpstk_MiscMath.i"
%include "gpstk_MJD.i"
//%include "gpstk_
%include "gpstk_MoonPosition.i"
%include "gpstk_MOPSWeight.i"
%include "gpstk_MSCBase.i"
%include "gpstk_MSCData.i"
//%include "gpstk_
%include "gpstk_MSCStore.i"
%include "gpstk_MSCStream.i"
%include "gpstk_NEDUtil.i"
%include "gpstk_ObsClockModel.i"
%include "gpstk_ObsEpochMap.i"
%include "gpstk_ObsID.i"
%include "gpstk_ObsRngDev.i"
%include "gpstk_OceanLoading.i"
%include "gpstk_orbitgroup.i"
%include "gpstk_ORDEpoch.i"
%include "gpstk_PCodeConst.i"
%include "gpstk_PoleTides.i"
%include "gpstk_PolyFit.i"
%include "gpstk_position.i"
//%include "gpstk_
//%include "gpstk_
%include "gpstk_RACRotation.i"
%include "gpstk_RinexEphemerisStore.i"
%include "gpstk_RinexMetBase.i"
//%include "gpstk_
%include "gpstk_RinexMetFilterOperators.i"
//%include "gpstk_
%include "gpstk_RinexMetStream.i"
%include "gpstk_RinexNavBase.i"
//%include "gpstk_
%include "gpstk_RinexNavFilterOperators.i"
//%include "gpstk_
%include "gpstk_RinexNavStream.i"
%include "gpstk_RinexObsBase.i"
//%include "gpstk_
%include "gpstk_RinexObsFilterOperators.i"
//%include "gpstk_
%include "gpstk_RinexObsID.i"
%include "gpstk_RinexObsStream.i"
%include "gpstk_RinexSatID.i"
%include "gpstk_RinexUtilities.i"
//%include "gpstk_
//%include "gpstk_
%include "gpstk_SatDataReader.i"
//%include "gpstk_
%include "gpstk_SEMBase.i"
//%include "gpstk_
//%include "gpstk_
%include "gpstk_SEMStream.i"
%include "gpstk_SimpleIURAWeight.i"
//%include "gpstk_
%include "gpstk_SMODFData.i"
%include "gpstk_SMODFStream.i"
%include "gpstk_SolidTides.i"
//%include "gpstk_
%include "gpstk_SourceID.i"
%include "gpstk_SP3Base.i"
//%include "gpstk_
%include "gpstk_SP3EphemerisStore.i"
//%include "gpstk_
%include "gpstk_SP3SatID.i"
%include "gpstk_SP3Stream.i"
%include "gpstk_SpecialFunctions.i"
%include "gpstk_Stats.i"
%include "gpstk_stl_helpers.i"
//%include "gpstk_
%include "gpstk_StudentDistribution.i"
%include "gpstk_SunPosition.i"
//%include "gpstk_
%include "gpstk_SVNumXRef.i"
%include "gpstk_SVPCodeGen.i"
%include "gpstk_SystemTime.i"
%include "gpstk_TabularEphemerisStore.i"
%include "gpstk_TimeConstants.i"
%include "gpstk_TimeConverters.i"
%include "gpstk_TimeNamedFileStream.i"
%include "gpstk_TimeString.i"
%include "gpstk_TimeTag.i"
%include "gpstk_Triple.i"
%include "gpstk_TropModel.i"
%include "gpstk_TypeID.i"
%include "gpstk_UnixTime.i"
%include "gpstk_ValidType.i"
%include "gpstk_VectorBase.i"
//%include "gpstk_
//%include "gpstk_
%include "gpstk_WeightBase.i"
%include "gpstk_WGS84Ellipsoid.i"
%include "gpstk_WGS84Geoid.i"
%include "gpstk_WxObsMap.i"
%include "gpstk_X1Sequence.i"
%include "gpstk_X2Sequence.i"
%inlcude "gpstk_Xvt.i"
%inlcude "gpstk_XvtStore.i"
%inlcude "gpstk_YDSTime.i"
%inlcude "gpstk_YumaAlmanacStore.i"
%inlcude "gpstk_YumaBase.i"
%inlcude "gpstk_YumaData.i"
%inlcude "gpstk_YumaHeader.i"
%inlcude "gpstk_YumaStream.i"
%include "gpstk_Zcount.i"


