#!/bin/bash
#
# Run bibtex on each .aux file in the present directory.
#
# Copyright (C) 2004 Thorsten Hansen
#
#
# This work may be distributed and/or modified under the conditions of
# the LaTeX Project Public License, either version 1.3 of this license
# or any later version. The latest version of this license is in
# http://www.latex-project.org/lppl.txt and version 1.3 or later is
# part of all distributions of LaTeX version 2003/12/01 or
# later.

for file in *.aux ; do
  bibtex `basename $file .aux`
done
