%!PS-Adobe EPSF-3.0
%%BoundingBox: 0 0 612 792
%% Created by vdraw
%%
% Rectangle
newpath
0 792 moveto
612 792 lineto
612 0 lineto
0 0 lineto
closepath
gsave
1 1 1 setrgbcolor 
fill
grestore
1 1 1 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/center { dup stringwidth pop 2 div neg 0 rmoveto } def
/Helvetica-Bold findfont
29.76 scalefont setfont
0 0 0 setrgbcolor 
newpath
306 715.92 moveto
(GPS Calendar 2015) center show
% Text
/Times findfont
13.392 scalefont setfont
0 0 0 setrgbcolor 
newpath
306 43.418 moveto
(Generated using the GPS Toolkit) center show
% Text
0 0 0 setrgbcolor 
newpath
306 28.018 moveto
(http://www.gpstk.org/) center show
% Text
/Helvetica-Bold findfont
14.103 scalefont setfont
0 0 0 setrgbcolor 
newpath
118 663.45 moveto
(January) center show
% Rectangle
newpath
33 656.39 moveto
203 656.39 lineto
203 633.83 lineto
33 633.83 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
50 640.6 moveto
(1825) center show
% Text
0 0 0 setrgbcolor 
newpath
50 618.03 moveto
(1826) center show
% Rectangle
newpath
33 611.26 moveto
203 611.26 lineto
203 588.7 lineto
33 588.7 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
50 595.47 moveto
(1827) center show
% Text
0 0 0 setrgbcolor 
newpath
50 572.9 moveto
(1828) center show
% Rectangle
newpath
33 566.13 moveto
203 566.13 lineto
203 543.57 lineto
33 543.57 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
50 550.34 moveto
(1829) center show
% Text
0 0 0 setrgbcolor 
newpath
154.43 645.11 moveto
(1) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/right { dup stringwidth pop neg 0 rmoveto } def
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
164.14 636.09 moveto
(1) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
173.86 645.11 moveto
(2) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
183.57 636.09 moveto
(2) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
193.29 645.11 moveto
(3) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
203 636.09 moveto
(3) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
76.714 622.55 moveto
(4) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
86.429 613.52 moveto
(4) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
96.143 622.55 moveto
(5) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
105.86 613.52 moveto
(5) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
115.57 622.55 moveto
(6) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
125.29 613.52 moveto
(6) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
135 622.55 moveto
(7) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
144.71 613.52 moveto
(7) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
154.43 622.55 moveto
(8) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
164.14 613.52 moveto
(8) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
173.86 622.55 moveto
(9) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
183.57 613.52 moveto
(9) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
193.29 622.55 moveto
(10) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
203 613.52 moveto
(10) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
76.714 599.98 moveto
(11) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
86.429 590.96 moveto
(11) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
96.143 599.98 moveto
(12) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
105.86 590.96 moveto
(12) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
115.57 599.98 moveto
(13) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
125.29 590.96 moveto
(13) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
135 599.98 moveto
(14) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
144.71 590.96 moveto
(14) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
154.43 599.98 moveto
(15) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
164.14 590.96 moveto
(15) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
173.86 599.98 moveto
(16) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
183.57 590.96 moveto
(16) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
193.29 599.98 moveto
(17) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
203 590.96 moveto
(17) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
76.714 577.42 moveto
(18) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
86.429 568.39 moveto
(18) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
96.143 577.42 moveto
(19) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
105.86 568.39 moveto
(19) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
115.57 577.42 moveto
(20) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
125.29 568.39 moveto
(20) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
135 577.42 moveto
(21) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
144.71 568.39 moveto
(21) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
154.43 577.42 moveto
(22) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
164.14 568.39 moveto
(22) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
173.86 577.42 moveto
(23) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
183.57 568.39 moveto
(23) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
193.29 577.42 moveto
(24) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
203 568.39 moveto
(24) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
76.714 554.85 moveto
(25) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
86.429 545.83 moveto
(25) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
96.143 554.85 moveto
(26) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
105.86 545.83 moveto
(26) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
115.57 554.85 moveto
(27) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
125.29 545.83 moveto
(27) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
135 554.85 moveto
(28) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
144.71 545.83 moveto
(28) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
154.43 554.85 moveto
(29) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
164.14 545.83 moveto
(29) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
173.86 554.85 moveto
(30) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
183.57 545.83 moveto
(30) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
193.29 554.85 moveto
(31) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
203 545.83 moveto
(31) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Helvetica-Bold findfont
14.103 scalefont setfont
0 0 0 setrgbcolor 
newpath
306 663.45 moveto
(February) center show
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
238 636.65 moveto
(1830) center show
% Rectangle
newpath
221 628.19 moveto
391 628.19 lineto
391 599.98 lineto
221 599.98 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
238 608.44 moveto
(1831) center show
% Text
0 0 0 setrgbcolor 
newpath
238 580.24 moveto
(1832) center show
% Rectangle
newpath
221 571.78 moveto
391 571.78 lineto
391 543.57 lineto
221 543.57 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
238 552.03 moveto
(1833) center show
% Text
0 0 0 setrgbcolor 
newpath
264.71 642.29 moveto
(1) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
274.43 631.01 moveto
(32) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
284.14 642.29 moveto
(2) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
293.86 631.01 moveto
(33) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
303.57 642.29 moveto
(3) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
313.29 631.01 moveto
(34) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
323 642.29 moveto
(4) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
332.71 631.01 moveto
(35) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
342.43 642.29 moveto
(5) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
352.14 631.01 moveto
(36) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
361.86 642.29 moveto
(6) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
371.57 631.01 moveto
(37) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
381.29 642.29 moveto
(7) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
391 631.01 moveto
(38) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
264.71 614.09 moveto
(8) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
274.43 602.8 moveto
(39) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
284.14 614.09 moveto
(9) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
293.86 602.8 moveto
(40) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
303.57 614.09 moveto
(10) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
313.29 602.8 moveto
(41) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
323 614.09 moveto
(11) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
332.71 602.8 moveto
(42) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
342.43 614.09 moveto
(12) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
352.14 602.8 moveto
(43) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
361.86 614.09 moveto
(13) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
371.57 602.8 moveto
(44) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
381.29 614.09 moveto
(14) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
391 602.8 moveto
(45) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
264.71 585.88 moveto
(15) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
274.43 574.6 moveto
(46) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
284.14 585.88 moveto
(16) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
293.86 574.6 moveto
(47) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
303.57 585.88 moveto
(17) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
313.29 574.6 moveto
(48) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
323 585.88 moveto
(18) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
332.71 574.6 moveto
(49) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
342.43 585.88 moveto
(19) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
352.14 574.6 moveto
(50) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
361.86 585.88 moveto
(20) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
371.57 574.6 moveto
(51) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
381.29 585.88 moveto
(21) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
391 574.6 moveto
(52) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
264.71 557.67 moveto
(22) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
274.43 546.39 moveto
(53) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
284.14 557.67 moveto
(23) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
293.86 546.39 moveto
(54) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
303.57 557.67 moveto
(24) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
313.29 546.39 moveto
(55) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
323 557.67 moveto
(25) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
332.71 546.39 moveto
(56) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
342.43 557.67 moveto
(26) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
352.14 546.39 moveto
(57) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
361.86 557.67 moveto
(27) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
371.57 546.39 moveto
(58) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
11.282 scalefont setfont
0 0 0 setrgbcolor 
newpath
381.29 557.67 moveto
(28) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.6156 scalefont setfont
0 0 1 setrgbcolor 
newpath
391 546.39 moveto
(59) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Helvetica-Bold findfont
14.103 scalefont setfont
0 0 0 setrgbcolor 
newpath
494 663.45 moveto
(March) center show
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
426 640.6 moveto
(1834) center show
% Rectangle
newpath
409 633.83 moveto
579 633.83 lineto
579 611.26 lineto
409 611.26 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
426 618.03 moveto
(1835) center show
% Text
0 0 0 setrgbcolor 
newpath
426 595.47 moveto
(1836) center show
% Rectangle
newpath
409 588.7 moveto
579 588.7 lineto
579 566.13 lineto
409 566.13 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
426 572.9 moveto
(1837) center show
% Text
0 0 0 setrgbcolor 
newpath
426 550.34 moveto
(1838) center show
% Text
0 0 0 setrgbcolor 
newpath
452.71 645.11 moveto
(1) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
462.43 636.09 moveto
(60) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
472.14 645.11 moveto
(2) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
481.86 636.09 moveto
(61) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
491.57 645.11 moveto
(3) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
501.29 636.09 moveto
(62) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
511 645.11 moveto
(4) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
520.71 636.09 moveto
(63) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
530.43 645.11 moveto
(5) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
540.14 636.09 moveto
(64) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
549.86 645.11 moveto
(6) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
559.57 636.09 moveto
(65) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
569.29 645.11 moveto
(7) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
579 636.09 moveto
(66) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
452.71 622.55 moveto
(8) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
462.43 613.52 moveto
(67) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
472.14 622.55 moveto
(9) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
481.86 613.52 moveto
(68) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
491.57 622.55 moveto
(10) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
501.29 613.52 moveto
(69) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
511 622.55 moveto
(11) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
520.71 613.52 moveto
(70) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
530.43 622.55 moveto
(12) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
540.14 613.52 moveto
(71) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
549.86 622.55 moveto
(13) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
559.57 613.52 moveto
(72) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
569.29 622.55 moveto
(14) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
579 613.52 moveto
(73) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
452.71 599.98 moveto
(15) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
462.43 590.96 moveto
(74) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
472.14 599.98 moveto
(16) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
481.86 590.96 moveto
(75) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
491.57 599.98 moveto
(17) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
501.29 590.96 moveto
(76) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
511 599.98 moveto
(18) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
520.71 590.96 moveto
(77) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
530.43 599.98 moveto
(19) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
540.14 590.96 moveto
(78) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
549.86 599.98 moveto
(20) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
559.57 590.96 moveto
(79) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
569.29 599.98 moveto
(21) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
579 590.96 moveto
(80) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
452.71 577.42 moveto
(22) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
462.43 568.39 moveto
(81) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
472.14 577.42 moveto
(23) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
481.86 568.39 moveto
(82) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
491.57 577.42 moveto
(24) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
501.29 568.39 moveto
(83) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
511 577.42 moveto
(25) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
520.71 568.39 moveto
(84) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
530.43 577.42 moveto
(26) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
540.14 568.39 moveto
(85) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
549.86 577.42 moveto
(27) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
559.57 568.39 moveto
(86) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
569.29 577.42 moveto
(28) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
579 568.39 moveto
(87) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
452.71 554.85 moveto
(29) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
462.43 545.83 moveto
(88) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
472.14 554.85 moveto
(30) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
481.86 545.83 moveto
(89) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
491.57 554.85 moveto
(31) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
501.29 545.83 moveto
(90) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Helvetica-Bold findfont
14.103 scalefont setfont
0 0 0 setrgbcolor 
newpath
118 504.42 moveto
(April) center show
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
50 481.57 moveto
(1838) center show
% Rectangle
newpath
33 474.8 moveto
203 474.8 lineto
203 452.23 lineto
33 452.23 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
50 459 moveto
(1839) center show
% Text
0 0 0 setrgbcolor 
newpath
50 436.44 moveto
(1840) center show
% Rectangle
newpath
33 429.67 moveto
203 429.67 lineto
203 407.1 lineto
33 407.1 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
50 413.87 moveto
(1841) center show
% Text
0 0 0 setrgbcolor 
newpath
50 391.31 moveto
(1842) center show
% Text
0 0 0 setrgbcolor 
newpath
135 486.08 moveto
(1) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
144.71 477.06 moveto
(91) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
154.43 486.08 moveto
(2) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
164.14 477.06 moveto
(92) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
173.86 486.08 moveto
(3) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
183.57 477.06 moveto
(93) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
193.29 486.08 moveto
(4) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
203 477.06 moveto
(94) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
76.714 463.52 moveto
(5) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
86.429 454.49 moveto
(95) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
96.143 463.52 moveto
(6) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
105.86 454.49 moveto
(96) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
115.57 463.52 moveto
(7) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
125.29 454.49 moveto
(97) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
135 463.52 moveto
(8) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
144.71 454.49 moveto
(98) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
154.43 463.52 moveto
(9) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
164.14 454.49 moveto
(99) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
173.86 463.52 moveto
(10) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
183.57 454.49 moveto
(100) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
193.29 463.52 moveto
(11) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
203 454.49 moveto
(101) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
76.714 440.95 moveto
(12) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
86.429 431.93 moveto
(102) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
96.143 440.95 moveto
(13) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
105.86 431.93 moveto
(103) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
115.57 440.95 moveto
(14) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
125.29 431.93 moveto
(104) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
135 440.95 moveto
(15) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
144.71 431.93 moveto
(105) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
154.43 440.95 moveto
(16) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
164.14 431.93 moveto
(106) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
173.86 440.95 moveto
(17) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
183.57 431.93 moveto
(107) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
193.29 440.95 moveto
(18) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
203 431.93 moveto
(108) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
76.714 418.39 moveto
(19) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
86.429 409.36 moveto
(109) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
96.143 418.39 moveto
(20) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
105.86 409.36 moveto
(110) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
115.57 418.39 moveto
(21) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
125.29 409.36 moveto
(111) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
135 418.39 moveto
(22) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
144.71 409.36 moveto
(112) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
154.43 418.39 moveto
(23) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
164.14 409.36 moveto
(113) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
173.86 418.39 moveto
(24) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
183.57 409.36 moveto
(114) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
193.29 418.39 moveto
(25) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
203 409.36 moveto
(115) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
76.714 395.82 moveto
(26) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
86.429 386.8 moveto
(116) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
96.143 395.82 moveto
(27) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
105.86 386.8 moveto
(117) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
115.57 395.82 moveto
(28) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
125.29 386.8 moveto
(118) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
135 395.82 moveto
(29) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
144.71 386.8 moveto
(119) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
154.43 395.82 moveto
(30) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
164.14 386.8 moveto
(120) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Helvetica-Bold findfont
14.103 scalefont setfont
0 0 0 setrgbcolor 
newpath
306 504.42 moveto
(May) center show
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
238 484.2 moveto
(1842) center show
% Rectangle
newpath
221 478.56 moveto
391 478.56 lineto
391 459.76 lineto
221 459.76 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
238 465.4 moveto
(1843) center show
% Text
0 0 0 setrgbcolor 
newpath
238 446.59 moveto
(1844) center show
% Rectangle
newpath
221 440.95 moveto
391 440.95 lineto
391 422.15 lineto
221 422.15 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
238 427.79 moveto
(1845) center show
% Text
0 0 0 setrgbcolor 
newpath
238 408.99 moveto
(1846) center show
% Rectangle
newpath
221 403.34 moveto
391 403.34 lineto
391 384.54 lineto
221 384.54 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
238 390.18 moveto
(1847) center show
% Text
0 0 0 setrgbcolor 
newpath
361.86 487.96 moveto
(1) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
371.57 480.44 moveto
(121) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
381.29 487.96 moveto
(2) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
391 480.44 moveto
(122) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
264.71 469.16 moveto
(3) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
274.43 461.64 moveto
(123) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
284.14 469.16 moveto
(4) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
293.86 461.64 moveto
(124) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
303.57 469.16 moveto
(5) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
313.29 461.64 moveto
(125) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
323 469.16 moveto
(6) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
332.71 461.64 moveto
(126) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
342.43 469.16 moveto
(7) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
352.14 461.64 moveto
(127) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
361.86 469.16 moveto
(8) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
371.57 461.64 moveto
(128) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
381.29 469.16 moveto
(9) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
391 461.64 moveto
(129) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
264.71 450.35 moveto
(10) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
274.43 442.83 moveto
(130) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
284.14 450.35 moveto
(11) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
293.86 442.83 moveto
(131) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
303.57 450.35 moveto
(12) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
313.29 442.83 moveto
(132) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
323 450.35 moveto
(13) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
332.71 442.83 moveto
(133) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
342.43 450.35 moveto
(14) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
352.14 442.83 moveto
(134) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
361.86 450.35 moveto
(15) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
371.57 442.83 moveto
(135) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
381.29 450.35 moveto
(16) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
391 442.83 moveto
(136) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
264.71 431.55 moveto
(17) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
274.43 424.03 moveto
(137) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
284.14 431.55 moveto
(18) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
293.86 424.03 moveto
(138) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
303.57 431.55 moveto
(19) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
313.29 424.03 moveto
(139) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
323 431.55 moveto
(20) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
332.71 424.03 moveto
(140) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
342.43 431.55 moveto
(21) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
352.14 424.03 moveto
(141) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
361.86 431.55 moveto
(22) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
371.57 424.03 moveto
(142) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
381.29 431.55 moveto
(23) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
391 424.03 moveto
(143) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
264.71 412.75 moveto
(24) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
274.43 405.22 moveto
(144) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
284.14 412.75 moveto
(25) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
293.86 405.22 moveto
(145) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
303.57 412.75 moveto
(26) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
313.29 405.22 moveto
(146) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
323 412.75 moveto
(27) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
332.71 405.22 moveto
(147) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
342.43 412.75 moveto
(28) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
352.14 405.22 moveto
(148) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
361.86 412.75 moveto
(29) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
371.57 405.22 moveto
(149) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
381.29 412.75 moveto
(30) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
391 405.22 moveto
(150) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
264.71 393.94 moveto
(31) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
274.43 386.42 moveto
(151) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Helvetica-Bold findfont
14.103 scalefont setfont
0 0 0 setrgbcolor 
newpath
494 504.42 moveto
(June) center show
% Rectangle
newpath
409 497.36 moveto
579 497.36 lineto
579 474.8 lineto
409 474.8 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
426 481.57 moveto
(1847) center show
% Text
0 0 0 setrgbcolor 
newpath
426 459 moveto
(1848) center show
% Rectangle
newpath
409 452.23 moveto
579 452.23 lineto
579 429.67 lineto
409 429.67 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
426 436.44 moveto
(1849) center show
% Text
0 0 0 setrgbcolor 
newpath
426 413.87 moveto
(1850) center show
% Rectangle
newpath
409 407.1 moveto
579 407.1 lineto
579 384.54 lineto
409 384.54 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
426 391.31 moveto
(1851) center show
% Text
0 0 0 setrgbcolor 
newpath
472.14 486.08 moveto
(1) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
481.86 477.06 moveto
(152) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
491.57 486.08 moveto
(2) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
501.29 477.06 moveto
(153) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
511 486.08 moveto
(3) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
520.71 477.06 moveto
(154) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
530.43 486.08 moveto
(4) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
540.14 477.06 moveto
(155) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
549.86 486.08 moveto
(5) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
559.57 477.06 moveto
(156) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
569.29 486.08 moveto
(6) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
579 477.06 moveto
(157) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
452.71 463.52 moveto
(7) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
462.43 454.49 moveto
(158) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
472.14 463.52 moveto
(8) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
481.86 454.49 moveto
(159) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
491.57 463.52 moveto
(9) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
501.29 454.49 moveto
(160) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
511 463.52 moveto
(10) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
520.71 454.49 moveto
(161) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
530.43 463.52 moveto
(11) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
540.14 454.49 moveto
(162) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
549.86 463.52 moveto
(12) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
559.57 454.49 moveto
(163) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
569.29 463.52 moveto
(13) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
579 454.49 moveto
(164) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
452.71 440.95 moveto
(14) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
462.43 431.93 moveto
(165) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
472.14 440.95 moveto
(15) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
481.86 431.93 moveto
(166) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
491.57 440.95 moveto
(16) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
501.29 431.93 moveto
(167) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
511 440.95 moveto
(17) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
520.71 431.93 moveto
(168) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
530.43 440.95 moveto
(18) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
540.14 431.93 moveto
(169) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
549.86 440.95 moveto
(19) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
559.57 431.93 moveto
(170) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
569.29 440.95 moveto
(20) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
579 431.93 moveto
(171) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
452.71 418.39 moveto
(21) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
462.43 409.36 moveto
(172) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
472.14 418.39 moveto
(22) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
481.86 409.36 moveto
(173) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
491.57 418.39 moveto
(23) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
501.29 409.36 moveto
(174) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
511 418.39 moveto
(24) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
520.71 409.36 moveto
(175) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
530.43 418.39 moveto
(25) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
540.14 409.36 moveto
(176) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
549.86 418.39 moveto
(26) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
559.57 409.36 moveto
(177) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
569.29 418.39 moveto
(27) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
579 409.36 moveto
(178) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
452.71 395.82 moveto
(28) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
462.43 386.8 moveto
(179) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
472.14 395.82 moveto
(29) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
481.86 386.8 moveto
(180) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
491.57 395.82 moveto
(30) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
501.29 386.8 moveto
(181) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Helvetica-Bold findfont
14.103 scalefont setfont
0 0 0 setrgbcolor 
newpath
118 345.39 moveto
(July) center show
% Rectangle
newpath
33 338.33 moveto
203 338.33 lineto
203 315.77 lineto
33 315.77 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
50 322.54 moveto
(1851) center show
% Text
0 0 0 setrgbcolor 
newpath
50 299.97 moveto
(1852) center show
% Rectangle
newpath
33 293.2 moveto
203 293.2 lineto
203 270.64 lineto
33 270.64 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
50 277.41 moveto
(1853) center show
% Text
0 0 0 setrgbcolor 
newpath
50 254.84 moveto
(1854) center show
% Rectangle
newpath
33 248.07 moveto
203 248.07 lineto
203 225.51 lineto
33 225.51 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
50 232.28 moveto
(1855) center show
% Text
0 0 0 setrgbcolor 
newpath
135 327.05 moveto
(1) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
144.71 318.03 moveto
(182) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
154.43 327.05 moveto
(2) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
164.14 318.03 moveto
(183) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
173.86 327.05 moveto
(3) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
183.57 318.03 moveto
(184) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
193.29 327.05 moveto
(4) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
203 318.03 moveto
(185) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
76.714 304.49 moveto
(5) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
86.429 295.46 moveto
(186) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
96.143 304.49 moveto
(6) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
105.86 295.46 moveto
(187) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
115.57 304.49 moveto
(7) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
125.29 295.46 moveto
(188) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
135 304.49 moveto
(8) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
144.71 295.46 moveto
(189) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
154.43 304.49 moveto
(9) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
164.14 295.46 moveto
(190) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
173.86 304.49 moveto
(10) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
183.57 295.46 moveto
(191) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
193.29 304.49 moveto
(11) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
203 295.46 moveto
(192) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
76.714 281.92 moveto
(12) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
86.429 272.9 moveto
(193) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
96.143 281.92 moveto
(13) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
105.86 272.9 moveto
(194) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
115.57 281.92 moveto
(14) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
125.29 272.9 moveto
(195) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
135 281.92 moveto
(15) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
144.71 272.9 moveto
(196) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
154.43 281.92 moveto
(16) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
164.14 272.9 moveto
(197) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
173.86 281.92 moveto
(17) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
183.57 272.9 moveto
(198) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
193.29 281.92 moveto
(18) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
203 272.9 moveto
(199) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
76.714 259.36 moveto
(19) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
86.429 250.33 moveto
(200) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
96.143 259.36 moveto
(20) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
105.86 250.33 moveto
(201) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
115.57 259.36 moveto
(21) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
125.29 250.33 moveto
(202) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
135 259.36 moveto
(22) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
144.71 250.33 moveto
(203) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
154.43 259.36 moveto
(23) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
164.14 250.33 moveto
(204) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
173.86 259.36 moveto
(24) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
183.57 250.33 moveto
(205) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
193.29 259.36 moveto
(25) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
203 250.33 moveto
(206) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
76.714 236.79 moveto
(26) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
86.429 227.77 moveto
(207) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
96.143 236.79 moveto
(27) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
105.86 227.77 moveto
(208) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
115.57 236.79 moveto
(28) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
125.29 227.77 moveto
(209) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
135 236.79 moveto
(29) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
144.71 227.77 moveto
(210) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
154.43 236.79 moveto
(30) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
164.14 227.77 moveto
(211) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
173.86 236.79 moveto
(31) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
183.57 227.77 moveto
(212) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Helvetica-Bold findfont
14.103 scalefont setfont
0 0 0 setrgbcolor 
newpath
306 345.39 moveto
(August) center show
% Rectangle
newpath
221 338.33 moveto
391 338.33 lineto
391 319.53 lineto
221 319.53 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
238 325.17 moveto
(1855) center show
% Text
0 0 0 setrgbcolor 
newpath
238 306.37 moveto
(1856) center show
% Rectangle
newpath
221 300.73 moveto
391 300.73 lineto
391 281.92 lineto
221 281.92 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
238 287.56 moveto
(1857) center show
% Text
0 0 0 setrgbcolor 
newpath
238 268.76 moveto
(1858) center show
% Rectangle
newpath
221 263.12 moveto
391 263.12 lineto
391 244.31 lineto
221 244.31 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
238 249.96 moveto
(1859) center show
% Text
0 0 0 setrgbcolor 
newpath
238 231.15 moveto
(1860) center show
% Text
0 0 0 setrgbcolor 
newpath
381.29 328.93 moveto
(1) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
391 321.41 moveto
(213) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
264.71 310.13 moveto
(2) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
274.43 302.61 moveto
(214) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
284.14 310.13 moveto
(3) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
293.86 302.61 moveto
(215) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
303.57 310.13 moveto
(4) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
313.29 302.61 moveto
(216) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
323 310.13 moveto
(5) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
332.71 302.61 moveto
(217) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
342.43 310.13 moveto
(6) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
352.14 302.61 moveto
(218) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
361.86 310.13 moveto
(7) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
371.57 302.61 moveto
(219) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
381.29 310.13 moveto
(8) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
391 302.61 moveto
(220) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
264.71 291.32 moveto
(9) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
274.43 283.8 moveto
(221) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
284.14 291.32 moveto
(10) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
293.86 283.8 moveto
(222) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
303.57 291.32 moveto
(11) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
313.29 283.8 moveto
(223) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
323 291.32 moveto
(12) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
332.71 283.8 moveto
(224) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
342.43 291.32 moveto
(13) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
352.14 283.8 moveto
(225) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
361.86 291.32 moveto
(14) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
371.57 283.8 moveto
(226) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
381.29 291.32 moveto
(15) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
391 283.8 moveto
(227) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
264.71 272.52 moveto
(16) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
274.43 265 moveto
(228) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
284.14 272.52 moveto
(17) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
293.86 265 moveto
(229) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
303.57 272.52 moveto
(18) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
313.29 265 moveto
(230) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
323 272.52 moveto
(19) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
332.71 265 moveto
(231) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
342.43 272.52 moveto
(20) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
352.14 265 moveto
(232) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
361.86 272.52 moveto
(21) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
371.57 265 moveto
(233) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
381.29 272.52 moveto
(22) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
391 265 moveto
(234) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
264.71 253.72 moveto
(23) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
274.43 246.19 moveto
(235) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
284.14 253.72 moveto
(24) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
293.86 246.19 moveto
(236) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
303.57 253.72 moveto
(25) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
313.29 246.19 moveto
(237) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
323 253.72 moveto
(26) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
332.71 246.19 moveto
(238) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
342.43 253.72 moveto
(27) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
352.14 246.19 moveto
(239) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
361.86 253.72 moveto
(28) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
371.57 246.19 moveto
(240) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
381.29 253.72 moveto
(29) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
391 246.19 moveto
(241) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
264.71 234.91 moveto
(30) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
274.43 227.39 moveto
(242) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
7.5216 scalefont setfont
0 0 0 setrgbcolor 
newpath
284.14 234.91 moveto
(31) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
5.0771 scalefont setfont
0 0 1 setrgbcolor 
newpath
293.86 227.39 moveto
(243) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Helvetica-Bold findfont
14.103 scalefont setfont
0 0 0 setrgbcolor 
newpath
494 345.39 moveto
(September) center show
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
426 322.54 moveto
(1860) center show
% Rectangle
newpath
409 315.77 moveto
579 315.77 lineto
579 293.2 lineto
409 293.2 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
426 299.97 moveto
(1861) center show
% Text
0 0 0 setrgbcolor 
newpath
426 277.41 moveto
(1862) center show
% Rectangle
newpath
409 270.64 moveto
579 270.64 lineto
579 248.07 lineto
409 248.07 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
426 254.84 moveto
(1863) center show
% Text
0 0 0 setrgbcolor 
newpath
426 232.28 moveto
(1864) center show
% Text
0 0 0 setrgbcolor 
newpath
491.57 327.05 moveto
(1) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
501.29 318.03 moveto
(244) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
511 327.05 moveto
(2) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
520.71 318.03 moveto
(245) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
530.43 327.05 moveto
(3) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
540.14 318.03 moveto
(246) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
549.86 327.05 moveto
(4) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
559.57 318.03 moveto
(247) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
569.29 327.05 moveto
(5) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
579 318.03 moveto
(248) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
452.71 304.49 moveto
(6) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
462.43 295.46 moveto
(249) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
472.14 304.49 moveto
(7) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
481.86 295.46 moveto
(250) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
491.57 304.49 moveto
(8) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
501.29 295.46 moveto
(251) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
511 304.49 moveto
(9) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
520.71 295.46 moveto
(252) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
530.43 304.49 moveto
(10) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
540.14 295.46 moveto
(253) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
549.86 304.49 moveto
(11) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
559.57 295.46 moveto
(254) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
569.29 304.49 moveto
(12) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
579 295.46 moveto
(255) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
452.71 281.92 moveto
(13) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
462.43 272.9 moveto
(256) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
472.14 281.92 moveto
(14) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
481.86 272.9 moveto
(257) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
491.57 281.92 moveto
(15) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
501.29 272.9 moveto
(258) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
511 281.92 moveto
(16) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
520.71 272.9 moveto
(259) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
530.43 281.92 moveto
(17) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
540.14 272.9 moveto
(260) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
549.86 281.92 moveto
(18) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
559.57 272.9 moveto
(261) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
569.29 281.92 moveto
(19) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
579 272.9 moveto
(262) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
452.71 259.36 moveto
(20) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
462.43 250.33 moveto
(263) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
472.14 259.36 moveto
(21) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
481.86 250.33 moveto
(264) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
491.57 259.36 moveto
(22) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
501.29 250.33 moveto
(265) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
511 259.36 moveto
(23) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
520.71 250.33 moveto
(266) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
530.43 259.36 moveto
(24) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
540.14 250.33 moveto
(267) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
549.86 259.36 moveto
(25) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
559.57 250.33 moveto
(268) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
569.29 259.36 moveto
(26) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
579 250.33 moveto
(269) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
452.71 236.79 moveto
(27) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
462.43 227.77 moveto
(270) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
472.14 236.79 moveto
(28) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
481.86 227.77 moveto
(271) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
491.57 236.79 moveto
(29) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
501.29 227.77 moveto
(272) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
511 236.79 moveto
(30) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
520.71 227.77 moveto
(273) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Helvetica-Bold findfont
14.103 scalefont setfont
0 0 0 setrgbcolor 
newpath
118 186.36 moveto
(October) center show
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
50 163.51 moveto
(1864) center show
% Rectangle
newpath
33 156.74 moveto
203 156.74 lineto
203 134.17 lineto
33 134.17 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
50 140.94 moveto
(1865) center show
% Text
0 0 0 setrgbcolor 
newpath
50 118.38 moveto
(1866) center show
% Rectangle
newpath
33 111.61 moveto
203 111.61 lineto
203 89.045 lineto
33 89.045 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
50 95.814 moveto
(1867) center show
% Text
0 0 0 setrgbcolor 
newpath
50 73.249 moveto
(1868) center show
% Text
0 0 0 setrgbcolor 
newpath
154.43 168.02 moveto
(1) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
164.14 159 moveto
(274) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
173.86 168.02 moveto
(2) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
183.57 159 moveto
(275) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
193.29 168.02 moveto
(3) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
203 159 moveto
(276) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
76.714 145.46 moveto
(4) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
86.429 136.43 moveto
(277) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
96.143 145.46 moveto
(5) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
105.86 136.43 moveto
(278) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
115.57 145.46 moveto
(6) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
125.29 136.43 moveto
(279) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
135 145.46 moveto
(7) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
144.71 136.43 moveto
(280) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
154.43 145.46 moveto
(8) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
164.14 136.43 moveto
(281) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
173.86 145.46 moveto
(9) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
183.57 136.43 moveto
(282) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
193.29 145.46 moveto
(10) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
203 136.43 moveto
(283) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
76.714 122.89 moveto
(11) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
86.429 113.87 moveto
(284) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
96.143 122.89 moveto
(12) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
105.86 113.87 moveto
(285) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
115.57 122.89 moveto
(13) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
125.29 113.87 moveto
(286) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
135 122.89 moveto
(14) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
144.71 113.87 moveto
(287) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
154.43 122.89 moveto
(15) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
164.14 113.87 moveto
(288) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
173.86 122.89 moveto
(16) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
183.57 113.87 moveto
(289) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
193.29 122.89 moveto
(17) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
203 113.87 moveto
(290) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
76.714 100.33 moveto
(18) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
86.429 91.301 moveto
(291) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
96.143 100.33 moveto
(19) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
105.86 91.301 moveto
(292) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
115.57 100.33 moveto
(20) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
125.29 91.301 moveto
(293) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
135 100.33 moveto
(21) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
144.71 91.301 moveto
(294) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
154.43 100.33 moveto
(22) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
164.14 91.301 moveto
(295) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
173.86 100.33 moveto
(23) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
183.57 91.301 moveto
(296) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
193.29 100.33 moveto
(24) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
203 91.301 moveto
(297) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
76.714 77.762 moveto
(25) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
86.429 68.736 moveto
(298) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
96.143 77.762 moveto
(26) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
105.86 68.736 moveto
(299) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
115.57 77.762 moveto
(27) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
125.29 68.736 moveto
(300) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
135 77.762 moveto
(28) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
144.71 68.736 moveto
(301) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
154.43 77.762 moveto
(29) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
164.14 68.736 moveto
(302) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
173.86 77.762 moveto
(30) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
183.57 68.736 moveto
(303) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
193.29 77.762 moveto
(31) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
203 68.736 moveto
(304) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Helvetica-Bold findfont
14.103 scalefont setfont
0 0 0 setrgbcolor 
newpath
306 186.36 moveto
(November) center show
% Rectangle
newpath
221 179.3 moveto
391 179.3 lineto
391 156.74 lineto
221 156.74 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
238 163.51 moveto
(1869) center show
% Text
0 0 0 setrgbcolor 
newpath
238 140.94 moveto
(1870) center show
% Rectangle
newpath
221 134.17 moveto
391 134.17 lineto
391 111.61 lineto
221 111.61 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
238 118.38 moveto
(1871) center show
% Text
0 0 0 setrgbcolor 
newpath
238 95.814 moveto
(1872) center show
% Rectangle
newpath
221 89.045 moveto
391 89.045 lineto
391 66.48 lineto
221 66.48 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
238 73.249 moveto
(1873) center show
% Text
0 0 0 setrgbcolor 
newpath
264.71 168.02 moveto
(1) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
274.43 159 moveto
(305) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
284.14 168.02 moveto
(2) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
293.86 159 moveto
(306) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
303.57 168.02 moveto
(3) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
313.29 159 moveto
(307) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
323 168.02 moveto
(4) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
332.71 159 moveto
(308) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
342.43 168.02 moveto
(5) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
352.14 159 moveto
(309) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
361.86 168.02 moveto
(6) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
371.57 159 moveto
(310) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
381.29 168.02 moveto
(7) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
391 159 moveto
(311) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
264.71 145.46 moveto
(8) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
274.43 136.43 moveto
(312) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
284.14 145.46 moveto
(9) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
293.86 136.43 moveto
(313) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
303.57 145.46 moveto
(10) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
313.29 136.43 moveto
(314) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
323 145.46 moveto
(11) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
332.71 136.43 moveto
(315) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
342.43 145.46 moveto
(12) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
352.14 136.43 moveto
(316) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
361.86 145.46 moveto
(13) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
371.57 136.43 moveto
(317) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
381.29 145.46 moveto
(14) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
391 136.43 moveto
(318) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
264.71 122.89 moveto
(15) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
274.43 113.87 moveto
(319) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
284.14 122.89 moveto
(16) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
293.86 113.87 moveto
(320) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
303.57 122.89 moveto
(17) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
313.29 113.87 moveto
(321) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
323 122.89 moveto
(18) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
332.71 113.87 moveto
(322) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
342.43 122.89 moveto
(19) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
352.14 113.87 moveto
(323) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
361.86 122.89 moveto
(20) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
371.57 113.87 moveto
(324) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
381.29 122.89 moveto
(21) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
391 113.87 moveto
(325) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
264.71 100.33 moveto
(22) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
274.43 91.301 moveto
(326) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
284.14 100.33 moveto
(23) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
293.86 91.301 moveto
(327) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
303.57 100.33 moveto
(24) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
313.29 91.301 moveto
(328) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
323 100.33 moveto
(25) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
332.71 91.301 moveto
(329) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
342.43 100.33 moveto
(26) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
352.14 91.301 moveto
(330) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
361.86 100.33 moveto
(27) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
371.57 91.301 moveto
(331) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
381.29 100.33 moveto
(28) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
391 91.301 moveto
(332) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
264.71 77.762 moveto
(29) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
274.43 68.736 moveto
(333) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
284.14 77.762 moveto
(30) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
293.86 68.736 moveto
(334) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Helvetica-Bold findfont
14.103 scalefont setfont
0 0 0 setrgbcolor 
newpath
494 186.36 moveto
(December) center show
% Rectangle
newpath
409 179.3 moveto
579 179.3 lineto
579 156.74 lineto
409 156.74 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
426 163.51 moveto
(1873) center show
% Text
0 0 0 setrgbcolor 
newpath
426 140.94 moveto
(1874) center show
% Rectangle
newpath
409 134.17 moveto
579 134.17 lineto
579 111.61 lineto
409 111.61 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
426 118.38 moveto
(1875) center show
% Text
0 0 0 setrgbcolor 
newpath
426 95.814 moveto
(1876) center show
% Rectangle
newpath
409 89.045 moveto
579 89.045 lineto
579 66.48 lineto
409 66.48 lineto
closepath
gsave
0.90196 0.90196 0.90196 setrgbcolor 
fill
grestore
0.90196 0.90196 0.90196 setrgbcolor 
0 setlinewidth
[ ] 0 setdash 
stroke
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
0 0 0 setrgbcolor 
newpath
426 73.249 moveto
(1877) center show
% Text
0 0 0 setrgbcolor 
newpath
491.57 168.02 moveto
(1) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
501.29 159 moveto
(335) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
511 168.02 moveto
(2) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
520.71 159 moveto
(336) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
530.43 168.02 moveto
(3) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
540.14 159 moveto
(337) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
549.86 168.02 moveto
(4) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
559.57 159 moveto
(338) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
569.29 168.02 moveto
(5) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
579 159 moveto
(339) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
452.71 145.46 moveto
(6) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
462.43 136.43 moveto
(340) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
472.14 145.46 moveto
(7) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
481.86 136.43 moveto
(341) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
491.57 145.46 moveto
(8) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
501.29 136.43 moveto
(342) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
511 145.46 moveto
(9) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
520.71 136.43 moveto
(343) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
530.43 145.46 moveto
(10) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
540.14 136.43 moveto
(344) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
549.86 145.46 moveto
(11) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
559.57 136.43 moveto
(345) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
569.29 145.46 moveto
(12) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
579 136.43 moveto
(346) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
452.71 122.89 moveto
(13) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
462.43 113.87 moveto
(347) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
472.14 122.89 moveto
(14) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
481.86 113.87 moveto
(348) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
491.57 122.89 moveto
(15) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
501.29 113.87 moveto
(349) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
511 122.89 moveto
(16) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
520.71 113.87 moveto
(350) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
530.43 122.89 moveto
(17) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
540.14 113.87 moveto
(351) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
549.86 122.89 moveto
(18) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
559.57 113.87 moveto
(352) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
569.29 122.89 moveto
(19) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
579 113.87 moveto
(353) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
452.71 100.33 moveto
(20) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
462.43 91.301 moveto
(354) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
472.14 100.33 moveto
(21) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
481.86 91.301 moveto
(355) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
491.57 100.33 moveto
(22) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
501.29 91.301 moveto
(356) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
511 100.33 moveto
(23) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
520.71 91.301 moveto
(357) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
530.43 100.33 moveto
(24) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
540.14 91.301 moveto
(358) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
549.86 100.33 moveto
(25) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
559.57 91.301 moveto
(359) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
569.29 100.33 moveto
(26) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
579 91.301 moveto
(360) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
452.71 77.762 moveto
(27) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
462.43 68.736 moveto
(361) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
472.14 77.762 moveto
(28) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
481.86 68.736 moveto
(362) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
491.57 77.762 moveto
(29) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
501.29 68.736 moveto
(363) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
511 77.762 moveto
(30) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
520.71 68.736 moveto
(364) right show
0 0 0 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
9.0259 scalefont setfont
0 0 0 setrgbcolor 
newpath
530.43 77.762 moveto
(31) center show
0 0 1 setrgbcolor 
1 setlinewidth
[ ] 0 setdash 
% Text
/Times-Bold findfont
6.0925 scalefont setfont
0 0 1 setrgbcolor 
newpath
540.14 68.736 moveto
(365) right show
