
        Month/Day/Year H:M:S            07/19/2015 00:00:00
        Modified Julian Date            57222.000000000
        GPSweek DayOfWeek SecOfWeek     830 0      0.000000
        FullGPSweek Zcount              1854      0
        Year DayOfYear SecondOfDay      2015 200     0.000000
        Unix: Second Microsecond        1437264000      0
        Zcount: 29-bit (32-bit)         435159040 (972029952)


