
        Month/Day/Year H:M:S            07/19/2015 00:01:40
        Modified Julian Date            57222.001157407
        GPSweek DayOfWeek SecOfWeek     830 0    100.000000
        FullGPSweek Zcount              1854     66
        Year DayOfYear SecondOfDay      2015 200   100.000000
        Unix: Second Microsecond        1437264100      0
        Zcount: 29-bit (32-bit)         435159106 (972030018)


